### ISSUE TITLE
Unhandled Exception when downloading PDF

### ISSUE THREAD

**Issue by SirMarth01** [ElPumpo/TinyNvidiaUpdateChecker#10]
```
Unhandled Exception: System.InvalidOperationException: Cannot start process because a file name has not been provided.
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at TinyNvidiaUpdateChecker.MainConsole.downloadDriver()
   at TinyNvidiaUpdateChecker.MainConsole.Main(String[] args)
```
Occurs in v1.4.1. HtmlAgilityPack.dll was located in same folder as the program.
Steps to reproduce:
1.) Run program.
2.) Agree to download updated drivers. After selecting location, drivers successfully download.
3.) At prompt to view release PDF, hit Yes. Program immediately crashes.

**Comment by ElPumpo** [comment]
Aight, first off thanks for using TinyNvidiaUpdateChecker! Try running it with the --debug parameter and check if pdfURL was set to something, and do you even have a pdf reader installed on your computer? That might be the cause of the issue..

**Comment by ElPumpo** [comment]
After some debugging it has been confirmed that the cause of `InvalidOperationException` when trying to open the pdf file is because there is no application set to open `.pdf` files.

**Comment by SirMarth01** [comment]
I do have a PDF reader installed (SumatraPDF 64-bit), and it is set as the default PDF reader in Windows. I thought for a second that Windows 10 had (in)conveniently forgotten about it, but it is installed and does work. pdfURL wasn't set, though. Even tried switching to Sumatra 32-bit and Microsoft Edge. The problem isn't lack of a PDF viewer, it's not getting the pdfURL.

**Comment by ElPumpo** [comment]
And are you 100% sure that you are running `v1.4.1` and not `v1.4.0`? You can check this by using the `--version` parameter. If `pdfURL` equals `null` the application will not ask you if you want to see the release notes - the check was added in `v1.4.1`.

**Comment by SirMarth01** [comment]
Screenshot for you. Definitely v1.4.1. Definitely still showing me if I want to see release notes. I know I used --force-dl, but it was doing the same thing before I updated the drivers. Even if I don't use --force-dl, pdfURL isn't set.

![untitled](https://cloud.githubusercontent.com/assets/23131433/19831060/40bdec9c-9dcf-11e6-9567-98d236ef7b29.png)

**Comment by ElPumpo** [comment]
[TinyNvidiaUpdateChecker.zip](https://github.com/ElPumpo/TinyNvidiaUpdateChecker/files/560097/TinyNvidiaUpdateChecker.zip) try that build if the issue is fixed

**Comment by SirMarth01** [comment]
`pdfURL` is still unusable, but it no longer asks if you want to see the release notes, so at least it won't crash.
![untitled](https://cloud.githubusercontent.com/assets/23131433/19832177/bdc88a38-9dea-11e6-8a4c-993610aa1c00.png)

**Comment by ElPumpo** [comment]
The cause for `pdfURL` to be null is because nvidia removed the release notes.

**Comment by ElPumpo** [comment]
Background: `gpuURL` was set to `space`, which is not `null`. The check before displaying the pdf question checks if it is null. I added `.Trim()` methods which removes misc chars from all the strings fetched from the NVIDIA website.

**Comment by SirMarth01** [comment]
> The cause for pdfURL to be null is because nvidia removed the release notes.

Not certain if this is either a miscommunication or a misunderstanding, but the release notes are still available, for example, [here's the latest one](http://us.download.nvidia.com/Windows/375.70/375.70-win10-win8-win7-desktop-release-notes.pdf). Your method of retrieving the release notes might need to be changed, but the release notes are still there.

**Comment by ElPumpo** [comment]
> Not certain if this is either a miscommunication or a misunderstanding, but the release notes are still available, for example, here's the latest one. Your method of retrieving the release notes might need to be changed, but the release notes are still there.

No my friend, the thing is that there is no release notes on the website itself. You can try this yourself by navigating to `processURL` and select `Additional Information`. There is no release notes available. This is not the first time NVIDIA has deleted release notes from their drivers from the download page.

**Comment by SirMarth01** [comment]
It's not linked on the [Nvidia page](http://www.nvidia.com/download/driverResults.aspx/110603/en-us), but it is linked on the [GeForce page](http://www.geforce.com/drivers/results/110603). From what I can tell, a consistent way to download them would be something along the lines of:

For desktop:
`pdfURL = "http://us.download.nvidia.com/Windows/" + onlineGPUDriverVersion + "/" + onlineGPUDriverVersion  + "-win10-win8-win7-desktop-release-notes.pdf"`

For mobile:
`pdfURL = "http://us.download.nvidia.com/Windows/" + onlineGPUDriverVersion + "/" + onlineGPUDriverVersion  + "-win10-win8-win7-notebook-release-notes.pdf"`

Then you can [get rid of lines 592-594](https://github.com/ElPumpo/TinyNvidiaUpdateChecker/blob/master/TinyNvidiaUpdateChecker/MainConsole.cs#L592), and insert new logic [while you're already identifying desktop or mobile](https://github.com/ElPumpo/TinyNvidiaUpdateChecker/blob/master/TinyNvidiaUpdateChecker/MainConsole.cs#L538), inserting defining `pdfURL` between lines 540-541 and between 543-544. The only possible downside I can imagine is if they put up release notes in multiple languages. (As far as I can tell, they don't.)

**Comment by ElPumpo** [comment]
https://github.com/ElPumpo/TinyNvidiaUpdateChecker/commit/53ce9df8d9bc59eb3e1c786e2c3c00144b8ec199#diff-5459f3b43e8938ca10b327da43540fa5R755

**Comment by ElPumpo** [comment]
To respond to your updated comment, I already changed all the fields to strings with proper stuff.
