### ISSUE TITLE
Only show driver updates when associated NVENC patches are available

### ISSUE THREAD

**Issue by burritosoftware** [ElPumpo/TinyNvidiaUpdateChecker#108]
TNUC is great for updating my video drivers, however I would prefer to only have it show an update if a patch for the driver I'm updating to is available. For context, NVENC has a video stream limit which prevents multiple apps from using it simultaneously. As such, I always patch my drivers to allow for this limit to be lifted. So, having the app be able to read from the patches repo on GitHub and check to see if the latest update has a patch would be appreciated (or, find the last known version with a patch, that's probably better)  

One way could be scanning this folder https://github.com/keylase/nvidia-patch/tree/master/win/win10_x64  
Another way could be parsing the markdown table in the README https://github.com/keylase/nvidia-patch/tree/master/win#readme

**Comment by ElPumpo** [comment]
This is not going to happen. Does not seem popular enough and I rely on another developer keeping his thing updated.
