### ISSUE TITLE
NOT AN ISSUE - THANKS!

### ISSUE THREAD

**Issue by Shituation** [ElPumpo/TinyNvidiaUpdateChecker#110]
Just wanted to give you my sincere thanks for developing and sharing this app, making us free from that bloatware "Gforce Experience" data mining crap. 
Nvidia doesn't have RSS on purpose so that if you want to get driver update notifications, you must use data mining apps like theirs.

Thank you again.

**Comment by ElPumpo** [comment]
Thanks <3
