### ISSUE TITLE
HD Audio Driver Should be included in minimal install

### ISSUE THREAD

**Issue by jonatino** [ElPumpo/TinyNvidiaUpdateChecker#111]
I tried using this to install a minimal driver after DDU, but it does not install nvidia's hdmi audio driver so my audio didnt work at all.

https://i.imgur.com/jw9lcff.png

Please add an option to install the HD Audio Driver

**Comment by Technetium1** [comment]
Open `C:\Users\YOUR-USERNAME-HERE\AppData\Local\Hawaii_Beach\TinyNvidiaUpdateChecker\app.config` and change minimal to false.

**Comment by ElPumpo** [comment]
This ties in with issue #28 allowing people to choose what they want. I'm way too lazy to implement this atm.
