### ISSUE TITLE
Cannot run quietly in new windows terminal on Windows 11

### ISSUE THREAD

**Issue by jiut** [ElPumpo/TinyNvidiaUpdateChecker#112]
When starting up, if you choose windows terminal as default terminal, it shows a blank window for a period of time even if it has a quiet argument.

**Comment by ElPumpo** [comment]
Well are you using the `--quiet` command line argument?

**Comment by jiut** [comment]
> Well are you using the `--quiet` command line argument?

Yes, If cmd is set as default, it runs quietly as expected.

**Comment by securemeister** [comment]
Can you try to place a '&' in front of the filename. eg:
& .\TinyNvidiaUpdateChecker.exe --quiet

**Comment by jiut** [comment]
> Can you try to place a '&' in front of the filename. eg:
> 
> & .\TinyNvidiaUpdateChecker.exe --quiet

No, it can't be placed in shortcut.

But I found there is a "Terminal" tab in shortcut's properties window. I tried to change "Default Terminal Application", but there is no option.

**Comment by ElPumpo** [comment]
I cannot reproduce this in Windows Terminal. Weird

**Comment by jiut** [comment]
> I cannot reproduce this in Windows Terminal. Weird

I forget to mention that mine is Windows 11 22H2

**Comment by ElPumpo** [comment]
Oh I am on Windows 10 that's probably why..

**Comment by ElPumpo** [comment]
Closing as I cannot reproduce this issue in W11

**Comment by jiut** [comment]
Shortcut is this, no other option.
`D:\Files\Programs\TinyNvidiaUpdateChecker\TinyNvidiaUpdateChecker.exe --quiet --confirm-dl`

https://github.com/ElPumpo/TinyNvidiaUpdateChecker/assets/52725935/0278ed5c-fc6a-478b-b936-370b780f0f45

**Comment by ElPumpo** [comment]
Try chosing "Minimized" 
![image](https://github.com/ElPumpo/TinyNvidiaUpdateChecker/assets/12564301/ac321310-42de-4546-85e7-509f82b091c3)

**Comment by jiut** [comment]
Thanks a lot.

**Comment by ElPumpo** [comment]
No worries. Im too lazy to add to wiki you can do that if you want
