### ISSUE TITLE
Invalid URI: The format of the URI could not be determined

### ISSUE THREAD

**Issue by mezdelex** [ElPumpo/TinyNvidiaUpdateChecker#114]
![image](https://user-images.githubusercontent.com/59997405/200125854-b068f22d-9d92-42b1-82ee-29f3dc89098d.png)

Sup, I'm getting this error whenever I try to update. Any clue what is all about? Thanks in advance.

**Comment by demitsuria** [comment]
I'm still getting this error on 1.14.7
