### ISSUE TITLE
shell_ipc_client UNAVAILABLE_RESOURCE error

### ISSUE THREAD

**Issue by Ethaniel-404** [ElPumpo/TinyNvidiaUpdateChecker#117]
It happens with the latest versión, 1.14.7, minimal install, Download only. The rest seems to work okay, though. Am I missing something? The blurred part is the user account on Windows 10.

![03](https://user-images.githubusercontent.com/52855817/200388459-bfd6aa58-d792-4914-a650-a0c43d102f50.jpg)

**Comment by ElPumpo** [comment]
Ugh Ill have to look at this when I'm back home. Seems like Nvidia broke more stuff but it's my fault my inplementation is unrealible I am surprised it even worked this long

**Comment by ElPumpo** [comment]
Do you have the same issue in v1.15.0? I recently changed a lot of code in that area perhaps it is no longer an issue.

**Comment by Ethaniel-404** [comment]
I'd love to, but Windows Defender started screaming like a banshee, something about Trojan:Win32/Wacatac.B!ml

**Comment by ElPumpo** [comment]
Haha well you have some other problems going on in your system. Fix them first.

**Comment by Ethaniel-404** [comment]
Looks perfect from here, I think you've got it!

![01](https://user-images.githubusercontent.com/52855817/202876979-dcf1ccf7-838f-4309-89bd-21354f55c855.jpg)

**Comment by ElPumpo** [comment]
Nice. Closing
