### ISSUE TITLE
Retrieving GPU information . . . ERROR!

### ISSUE THREAD

**Issue by ilkovicb** [ElPumpo/TinyNvidiaUpdateChecker#119]
TinyNvidiaUpdateChecker v1.14.7

Verifying internet connection . . . OK!

Verifying HAP MD5 hash . . . OK!

Searching for Updates . . . OK!

Retrieving GPU information . . . ERROR!
System.UriFormatException: Invalid URI: The Authority/Host could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at HtmlAgilityPack.HtmlWeb.Load(String url)
   at TinyNvidiaUpdateChecker.MainConsole.GpuInfo()
Your current GPU driver is newer than remote!
Your GPU drivers are up-to-date!

Press any key to exit...

Its on Windows 11, graphic card is GTX1080 Ti, my graphic driver was OLDER then remote :-)

**Comment by seancumming** [comment]
FWIW, I'm seeing the same error in nv_updater...
11/11/2022 3:56:36 PM - There was an Error at GraphicsInfo
Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at HtmlAgilityPack.HtmlWeb.Load(String url)
   at nv_updater.nvidia_helper.GetOnlineVersion(String Link)

Windows 10, 3080

**Comment by f33d13ack** [comment]
TinyNvidiaUpdateChecker v1.14.7

Verifying internet connection . . . OK!

Verifying HAP MD5 hash . . . OK!

Searching for Updates . . . OK!

Retrieving GPU information . . . ERROR!
System.UriFormatException: Invalid URI: The Authority/Host could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at HtmlAgilityPack.HtmlWeb.Load(String url)
   at TinyNvidiaUpdateChecker.MainConsole.GpuInfo()
Your current GPU driver is newer than remote!
Your GPU drivers are up-to-date!

Press any key to exit...

** Also getting the same error, Windows 10 Pro, 3080 version 526.47, new is 526.86 as of Nov 12, 2022.
** Same error on laptop, Windows 10 Home, 2070 Super, same versions as above.
** Also tested TinyNvidiaUpdateChecker v1.14.5 and v1.14.6, same errors.

**Comment by dmsheets377** [comment]
Exact same error here on all three of my computers, one with a 1080ti, one with a 1060 6gb, and one with a 3070 super. Only thing in common is that they are all running win 10 21h2 enterprise LTSC

**Comment by ElPumpo** [comment]
Okay I found the issue. It has to do with the language ID. Different values give different URL responces.

For example

![image](https://user-images.githubusercontent.com/12564301/202533713-4ef4ea03-e08e-40e8-b783-f2fea976d40c.png)

![image](https://user-images.githubusercontent.com/12564301/202533747-6e633df9-8f82-4066-ab24-15023a822f98.png)

**Comment by AlRlC** [comment]
good find! I did not think of that

**Comment by ElPumpo** [comment]
[TinyNvidiaUpdateChecker v1.5.0 beta 1.zip](https://github.com/ElPumpo/TinyNvidiaUpdateChecker/files/10036742/TinyNvidiaUpdateChecker.v1.5.0.beta.1.zip)

This is a beta of a complete code rewrite for getting driver information. It now uses the NVIDIA ajax service. The code is mostly based of https://github.com/ZenitH-AT/nvidia-update

**Comment by ilkovicb** [comment]
It seems works, thank you!

TinyNvidiaUpdateChecker v1.15.0

Verifying internet connection . . . OK!

Searching for Updates . . . OK!

Retrieving GPU information . . . OK!
Your GPU drivers are up-to-date!

Press any key to exit...

Lets wait for new drivers..... :-)

**Comment by ElPumpo** [comment]
Well yea use the `--debug` command line argument

**Comment by ElPumpo** [comment]
v1.15.0 has been released with a fix. Thanks for the waiting
