### ISSUE TITLE
Informal language

### ISSUE THREAD

**Issue by threekeys** [ElPumpo/TinyNvidiaUpdateChecker#12]
> i'm retarded 

https://github.com/ElPumpo/TinyNvidiaUpdateChecker/commit/936a4faa80bda91bd9da093caa9d7e746e728b1d

**Comment by ElPumpo** [comment]
I don't see the issue, neither is this in anyway related to the software.

**Comment by threekeys** [comment]
It certainly gives a poor first impression of the software.

**Comment by ElPumpo** [comment]
Hm.. I guess so. Looking at the commit titles, you're right, that will change.
