### ISSUE TITLE
Please remove the "press any key to exit"

### ISSUE THREAD

**Issue by Shituation** [ElPumpo/TinyNvidiaUpdateChecker#120]
So we can put your app as a scheduled task and we don't have to interact with it unless a new driver is found.

**Comment by Nopraz** [comment]
I think you need to use the `--quiet` argument in the command line if you want to use it in a scheduled task

**Comment by Shituation** [comment]
Good! I didn't know about that argument, thanks!

**Comment by ElPumpo** [comment]
Yea you're right the console should not be kept alive.. because it should be used in CMD. But the entire code needs a rewrite anyways with a cool looking UI n stuff..
