### ISSUE TITLE
Latest version is being recognized as malware

### ISSUE THREAD

**Issue by securemeister** [ElPumpo/TinyNvidiaUpdateChecker#124]
MS Defender is recognizing v1.15.0 as Trojan:Script/Wacatac.B!ml.
Unfortunately, I have no reference for other anti-virus systems.

**Comment by Technetium1** [comment]
Add to exceptions then! You can submit the file as a false positive here if you feel motivated: https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by ElPumpo** [comment]
How!

**Comment by securemeister** [comment]
no more wrong detection

**Comment by ElPumpo** [comment]
Will probably also happen with v1.15.1

**Comment by Technetium1** [comment]
Yep, it'll keep happening too! I have to do this every release for my ChocolateyUpdate since it's compiled with pyinstaller and unsigned. Just keep submitting as a false positive, it's all there is to do.

**Comment by Technetium1** [comment]
@ElPumpo rather than open a new issue: New release doesn't include the DLL, is it embedded now?

**Comment by ElPumpo** [comment]
Yes embedded now must be because of that..
