### ISSUE TITLE
Missing GPU metadata (gpuName: "Geforce RTX 2080 with Max-Q Design")

### ISSUE THREAD

**Issue by nukeclears** [ElPumpo/TinyNvidiaUpdateChecker#125]
GPU metadata doesn't exist for this card

gpuName: Geforce RTX 2080 with Max-Q Design
isNotebook: True

Did work back with 1.14

**Comment by f33d13ack** [comment]
Same thing here too, I wonder if this is a laptop issue?  EnvyUpdate shows driver available.

![Screenshot 2022-11-20 082229](https://user-images.githubusercontent.com/98703733/202913833-97c789e9-c1e5-48f1-a506-484409221d75.png)

![Screenshot 2022-11-20 082552](https://user-images.githubusercontent.com/98703733/202913921-ed1ec46e-cc1e-4792-adee-49883b28330e.png)
