### ISSUE TITLE
Missing GPU metadata (gpuName: "GeForce GTX 1050 Ti with Max-Q Design")

### ISSUE THREAD

**Issue by geomih** [ElPumpo/TinyNvidiaUpdateChecker#126]
TinyNvidiaUpdateChecker v1.15.0
Verifying internet connection . . . OK!
Searching for Updates . . . OK!
Retrieving GPU information . . . ERROR!
GPU metadata for your card does not exist! Please file an issue on GitHub and include the following information:
gpuName:    GeForce GTX 1050 Ti with Max-Q Design
isNotebook: True

**Comment by ElPumpo** [comment]
Yea the "with Max-Q Design" is not a part of the nvidia-data repo. But I think we can just remove that from the name as they use the same drivers.

**Comment by geomih** [comment]
Thanks a lot! v1.15.1 works, it just downloaded a driver update.

**Comment by ElPumpo** [comment]
Super!
