### ISSUE TITLE
GPU metadata for your card does not exist

### ISSUE THREAD

**Issue by michas1e4** [ElPumpo/TinyNvidiaUpdateChecker#127]
While starting TinyNvidiaUpdateChecker on my Surface Book i get these message:

_Retrieving GPU informationen ... ERROR!
GPU metadata for your card does not exist! Please file an issue on GitHub and include the following information:
gpuName: GeForce GTX 1660 Ti with Max-Q Design
isNotebook: True_

So i do so.

Greetings

**Comment by ElPumpo** [comment]
Is this on v1.15.1 or v1.15.0?

**Comment by qcksylvr** [comment]
I am having a similar issue:

TinyNvidiaUpdateChecker v1.15.1

Verifying internet connect . . . OK!

Retrieving GPU information . . . ERROR!
GPU metadata for your card does not exist! Please file an issue on GitHub and include the following information:
gpuName: GeForce 940MX
isNotebook: False

**Comment by ElPumpo** [comment]
@qcksylvr is your computer a notebook or desktop pc?

**Comment by qcksylvr** [comment]
It's a notebook. Thanks!

**Comment by renitec** [comment]
Hi! i'm having a different one, but with same conclusion.

![Tinynvidia](https://user-images.githubusercontent.com/119073471/204038775-9a8cee19-b457-4d1e-b510-5c5aaedcca24.jpg)

**Comment by renitec** [comment]
I'm on desktop pc.

**Comment by ElPumpo** [comment]
@qcksylvr yea that's weird because `isNotebook` is reported as `false`. Uuugh. Open powershell and input the following

` Get-WmiObject -class win32_systemenclosure | select  Caption,chassisTypes`

Please show a screenshot of the responce. I probably don't have your chassis type in my code.

@renitec first of all why is the update check not working 👁️ Second it's weird your GPU is in the metadata list. Is there perhaps some error in the `responce` returning null.. Have you always had this WebException error?

**Comment by qcksylvr** [comment]
Results from the command:

Caption          chassisTypes
-------          ------------
System Enclosure {31}

**Comment by renitec** [comment]
Hi.
was working perfectly before.

**Comment by ElPumpo** [comment]
@renitec well something is wrong as even the update check is failing. Can you try this on another computer?

@qcksylvr okay thanks I will adress this in a fix

**Comment by renitec** [comment]
I've tried on my laptop, works fine. Could it be the init files on my PC?

**Comment by ElPumpo** [comment]
@qcksylvr v1.15.2 has been released I think i've fixed the issue. Can you please try this new version?

@renitec I don't really know what advise to give you something is very wrong why would there be a WebException on the search update code.. And you dont have other programs giving you issues?

**Comment by qcksylvr** [comment]
@ElPumpo - v1.15.2 appears to have fixed my issue - thank you.

**Comment by ElPumpo** [comment]
Closing due to no reply
