### ISSUE TITLE
4080 issue

### ISSUE THREAD

**Issue by DMT4all** [ElPumpo/TinyNvidiaUpdateChecker#128]
![image](https://user-images.githubusercontent.com/87603446/203267892-53eb76be-d421-4acb-915e-c6330f72a880.png)

**Comment by ElPumpo** [comment]
Yep confirmed 4080 not in the list.

**Comment by ZenitH-AT** [comment]
It's been fixed by https://github.com/ZenitH-AT/nvidia-data/commit/85def6de8c2d54f2c347965aa6cbf57f6a5ca8d5. Shouldn't happen in the future.

**Comment by ElPumpo** [comment]
Thanks 👍
