### ISSUE TITLE
GeForce RTX 2070 SUPER GPU metadata not existing

### ISSUE THREAD

**Issue by Mettkrieger** [ElPumpo/TinyNvidiaUpdateChecker#133]
Hey, upon exectuting TinyNvidiaUpdateChecker.v1.15.2.exe --force-dl I get an error message that the GPU metadata does not exist.

Retrieving GPU information
ERROR!
GPU metadata for your card does not exist! Please file an issue on GitHub and include the following information:
gpuName: GeForce RTX 2070 SUPER
isNotebook: False

Some additional information: It's a EVGA 2070 Super FTW3

**Comment by ZenitH-AT** [comment]
Recent update should have fixed the issue with Super GPUs... Seems like some GPUs report as "SUPER" and others as "Super".

Does running `Get-CimInstance Win32_VideoController | Select-Object Name` in PowerShell output exactly "NVIDIA GeForce RTX 2070 SUPER"?

Might need to add replace code for "SUPER" to "Super" @ElPumpo, basically the reverse of what was there before.

**Comment by Mettkrieger** [comment]
Output is: NVIDIA GeForce RTX 2070 SUPER

**Comment by ElPumpo** [comment]
Okay your call boss. Will your repo have SUPER in uppercase for all GPUs?

**Comment by ZenitH-AT** [comment]
Yes it should always be uppercase now, so just replace "Super" with "SUPER" again as it was before.

**Comment by ElPumpo** [comment]
https://github.com/ElPumpo/TinyNvidiaUpdateChecker/commit/e28626c2041bfa1eeee4438a2406cf504fc8d33b

**Comment by ElPumpo** [comment]
Okay issue is fixed for now, and a perm fix next TNUC update. The nvidia-data repo is also adressed. Thanks for letting us know when it doesn't work @Mettkrieger
