### ISSUE TITLE
WebException: The remote name could not be resolved: 'gfwsl.geforce.com'

### ISSUE THREAD

**Issue by Buck-duck** [ElPumpo/TinyNvidiaUpdateChecker#135]
i have been having this issue since v1.15.1

TinyNvidiaUpdateChecker v1.15.2

Arg: --debug
Arg: --force-dl

configFile: C:\Users\user\AppData\Local\Hawaii_Beach\TinyNvidiaUpdateChecker\app.config
CHECK_UPDATE: true
MINIMAL_INSTALL: true
DOWNLOAD_LOCATION: jp

Verifying internet connection . . . OK!

Searching for Updates . . . OK!
offlineVer: 1.15.2
onlineVer:  1.15.2

Retrieving GPU information . . .
Unhandled Exception: System.Net.WebException: The remote name could not be resolved: 'gfwsl.geforce.com'
   at System.Net.WebClient.OpenRead(Uri address)
   at TinyNvidiaUpdateChecker.MainConsole.ReadURL(String url)
   at TinyNvidiaUpdateChecker.MainConsole.GetDriverDownloadInfo(Int32 gpuId, Int32 osId, Int32 isDchDriver)
   at TinyNvidiaUpdateChecker.MainConsole.Main(String[] args)

**Comment by Buck-duck** [comment]
TinyNvidiaUpdateChecker v1.15.2

Arg: --debug
Arg: --force-dl

configFile: C:\Users\user\AppData\Local\Hawaii_Beach\TinyNvidiaUpdateChecker\app.config
CHECK_UPDATE: true
MINIMAL_INSTALL: true
DOWNLOAD_LOCATION: jp

Verifying internet connection . . . OK!

Searching for Updates . . . OK!
offlineVer: 1.15.2
onlineVer:  1.15.2

Retrieving GPU information . . .
Unhandled Exception: System.Net.WebException: The remote name could not be resolved: 'gfwsl.geforce.com'
   at System.Net.WebClient.OpenRead(Uri address)
   at TinyNvidiaUpdateChecker.MainConsole.ReadURL(String url)
   at TinyNvidiaUpdateChecker.MainConsole.GetDriverDownloadInfo(Int32 gpuId, Int32 osId, Int32 isDchDriver)
   at TinyNvidiaUpdateChecker.MainConsole.Main(String[] args)

**Comment by ElPumpo** [comment]
Really? Super strange. What country do you live in? I dont have this issue and I am assuming most don't either.

**Comment by Buck-duck** [comment]
I'm from India but the download location in Tinyupdatechecker is set to Japan for now.

**Comment by Buck-duck** [comment]
Yeah only v1.14.7 works v1.15.0 to v1.15.2 returns the same error.

**Comment by ElPumpo** [comment]
Super strange. What happens if you navigate to https://gfwsl.geforce.com/services_toolkit/services/com/nvidia/services/AjaxDriverService.php?func=DriverManualLookup&pfid=877&osID=57&dch=1

**Comment by Buck-duck** [comment]
The link does not work.

**Comment by Buck-duck** [comment]
Hey it works now i just remembered that i had used the Full Block-list from Moyster/BaiGfe page ( https://github.com/Moyster/BaiGfe ) to block telemetry. I just edited my C:\Windows\System32\drivers\etc\hosts file to remove the block-list and Tinyupdatechecker v1.15.2 works. I will be using the Lite Block-list since it doesn't effect the update checker. Thank you for looking into my problem you can close this issue now.

**Comment by ElPumpo** [comment]
Bruh haha
