### ISSUE TITLE
System.Net.WebException: The remote name could not be resolved: 'usdownload.nvidia.com'

### ISSUE THREAD

**Issue by Honusnap** [ElPumpo/TinyNvidiaUpdateChecker#139]
Hi guys,
Just installed the checker and got this message : 

Retrieving GPU information . . .
Unhandled Exception: System.Net.WebException: The remote name could not be resolved: 'usdownload.nvidia.com'
   at System.Net.HttpWebRequest.GetResponse()
   at TinyNvidiaUpdateChecker.MainConsole.Main(String[] args)

I'm on a Laptop, i7 4702 + HD4600 + 760M

I tried France and US as download countries, same error.

**Comment by ElPumpo** [comment]
Oh no! What happened here.. I will investigate

**Comment by Honusnap** [comment]
If you want further info, let me know.

**Comment by ElPumpo** [comment]
What OS?

**Comment by Honusnap** [comment]
Windows 10 - 20H2

**Comment by ElPumpo** [comment]
![image](https://user-images.githubusercontent.com/12564301/209719535-21e17be6-e6b2-4d3a-a115-dfaf45a4729b.png)

Okay so apparently for your GPU the URL is not `https://`, but instead `http://` which is weird. Most common... or I mean every GPU I encountered use the former

**Comment by ElPumpo** [comment]
Will be resolved in next update

**Comment by Honusnap** [comment]
Hello,
Just test both .. ;D

**Comment by ElPumpo** [comment]
@Honusnap was the issue not resolved?
