### ISSUE TITLE
ERROR: GPU metadata for your card does not exist

### ISSUE THREAD

**Issue by christmas-man** [ElPumpo/TinyNvidiaUpdateChecker#140]
TinyNvidiaUpdateChecker v1.15.3

Verifying internet connection . . . OK!

Searching for Updates . . . OK!

Retrieving GPU information . . . ERROR!
GPU metadata for your card does not exist! Please file an issue on GitHub and include the following information:

gpuName:    TITAN Xp COLLECTORS EDITION
isNotebook: False

Press any key to exit...

**Comment by christmas-man** [comment]
Here's the names I could find beyond the verbose name.
![image](https://user-images.githubusercontent.com/121069701/208744483-b3cac7c5-c984-423b-94b4-eeb726b6226d.png)

**Comment by ElPumpo** [comment]
Thanks! @ZenitH-AT help lol

**Comment by ZenitH-AT** [comment]
Looks like regex will need to be changed (see pull request). NVIDIA doesn't have a different product family ID for the collectors edition variant; they're both the same card really.

**Comment by Pkistampally** [comment]
Hello Elpumpo Samuel, Sorry if i spelled your name wrongly. my organization heavily relies on this Tiny nvidia update checker and recently we figured that it was failling as we were using V1.14. we have now updated to latets V1.15.3 but still get the above same issue posted by Christmas-man.  below is the error we get .. 

![image](https://user-images.githubusercontent.com/63632201/208801532-09a3edd0-fa96-4af0-b4f4-2ae1b22a87de.png)
![image](https://user-images.githubusercontent.com/63632201/208801594-96501684-da64-45ed-9d7c-93d3952a4f8a.png)

**Comment by ZenitH-AT** [comment]
@Pkistampally your issue doesn't seem to be the same as christmas-man's, since your exact GPU name reported by TinyNvidiaUpdateChecker is in fact included in the data repository [here](https://github.com/ZenitH-AT/nvidia-data/blob/main/gpu-data.json#L809).

My PR fixes christmas-man's issue by basically removing "COLLECTORS EDITION" from the GPU name, since the only difference between the base TITAN Xp and that one is cosmetic.

Might be best to open up a separate issue for this.

**Comment by ElPumpo** [comment]
@christmas-man this issue will be resolved when I release next update

@ZenitH-AT great work 👍👍

@Pkistampally please make a new issue

**Comment by Pkistampally** [comment]
Ohh Yeah , we have been using this since an year and this is only way we can keep Nvidia Vulnerabilities UpToDate. on almost 3000+ end user devices in our Org.  I am going to open a separate case .. please look into that. I tested this on multiple devices and See same issues..

**Comment by ElPumpo** [comment]
Wow really? Interesting
