### ISSUE TITLE
Retrieving GPU Information Error because networking issues

### ISSUE THREAD

**Issue by Pkistampally** [ElPumpo/TinyNvidiaUpdateChecker#142]
![image](https://user-images.githubusercontent.com/63632201/208949064-f59898f7-3979-4aa4-b57d-cbec8f2d2bf8.png)
![image](https://user-images.githubusercontent.com/63632201/208949092-6402868d-4b4f-4d07-b620-1ad935255e97.png)

**Comment by ElPumpo** [comment]
Yes this is a weird issue for sure. Perhaps NVIDIA left a whitespace after the GPU name? @ZenitH-AT any clues? Perhaps `.Trim()` the name?

**Comment by ZenitH-AT** [comment]
Yeah, I think https://raw.githubusercontent.com is being blocked... Maybe add a way to use built in gpu-data and os-data?

**Comment by ElPumpo** [comment]
Lol no way we need Nvidia API access anyways I dont want hardcoded metadata

**Comment by Pkistampally** [comment]
@ElPumpo @ZenitH-AT yes, the above two URLs are blocked in the organization level. anything with local files if we can point to that would be great. we have blocked it from MDATP (Microsoft Defender Advanced Threat Protection) for all users on their Laptops

**Comment by ElPumpo** [comment]
😂😂😂

**Comment by ElPumpo** [comment]
Is there a possibility to whitelist the URLs?

**Comment by ElPumpo** [comment]
@Pkistampally waiting for your reply

**Comment by Pkistampally** [comment]
Hello Sam, Hope you had great Christmas , We will not be able to  whitelist the URLs since it will effect all the GitHub domain. I spoke to Networking Team.
I tried to access this below 
https://gfwsl.geforce.com/services_toolkit/services/com/nvidia/services/AjaxDriverService.php
should we get any response from this URL ..?

**Comment by Pkistampally** [comment]
this is what I get when I browse using chrome on any laptop either relater to company or personal
when i enter full url the page is blank and when I remove the last .php part I get this.

![image](https://user-images.githubusercontent.com/63632201/209723786-bac5c774-a805-46d1-951a-a43410b38b7c.png)

**Comment by ElPumpo** [comment]
Hi and merry christmas.

Try 
https://gfwsl.geforce.com/services_toolkit/services/com/nvidia/services/AjaxDriverService.php?func=DriverManualLookup&pfid=756&osID=57&dch=1

Why aren't you able to whitelist two absolute URLs on github?

**Comment by Pkistampally** [comment]
the above url which you gave is working . so what would be our next step.
we blocked the raw.githubuserconsent.com its usually what all orgs do. just donot want users to download anything from github which may act like a threat
https://gfwsl.geforce.com/services_toolkit/services/com/nvidia/services/AjaxDriverService.php?func=DriverManualLookup&pfid=756&osID=57&dch=1

**Comment by ElPumpo** [comment]
Well why can you not allow the two absolute URLs I previously told you about as allowed?

**Comment by Ominousonion666** [comment]
Hey, I got the same error but I don't think those two 'githubusercontent' links are blocked. I can open them in the browser.

**Comment by ElPumpo** [comment]
@Ominousonion666 Hi. Please open a seperate issue

**Comment by ElPumpo** [comment]
Okay you won I will implement local metadata files🍾

**Comment by ElPumpo** [comment]
[TinyNvidiaUpdateChecker 1.15.5 beta 1.zip](https://github.com/ElPumpo/TinyNvidiaUpdateChecker/files/10340116/TinyNvidiaUpdateChecker.1.15.5.beta.1.zip)

Beta version with local metadata support. The file names must be:

- `gpu-data.json`
- `os-data.json`

If they don't exist then online version will be used

**Comment by Pkistampally** [comment]
Hello Samuel,
I have download the new 1.15.4 version and I still get same error..

![image](https://user-images.githubusercontent.com/63632201/210653980-2298f69d-a2cf-44e0-b4e7-99dbe6a512e5.png)

**Comment by ElPumpo** [comment]
Did you follow my instructions?

**Comment by Pkistampally** [comment]
Sorry, should I create any files with gpu-data.json  and  os-data.json  since I donot see any of these files in the zip file

**Comment by ElPumpo** [comment]
Yes create your own. Just copy paste from https://github.com/ZenitH-AT/nvidia-data or download the files from there

**Comment by Pkistampally** [comment]
Thank you. So I copied the two files from above location to local drive and also the beta.exe file in same folder and trying to run now.. I get .netruntime not found even though I download the version which is shown in the command
![image](https://user-images.githubusercontent.com/63632201/210683350-0228a9a6-94e7-4458-aa95-bfca502b2d94.png)

**Comment by Pkistampally** [comment]
![image](https://user-images.githubusercontent.com/63632201/210683412-986843b3-fc36-4679-9537-e0b511b22f01.png)

**Comment by Pkistampally** [comment]
![image](https://user-images.githubusercontent.com/63632201/210683558-03e2e718-14c1-4ad4-ba87-36ff3b3f0dba.png)

**Comment by ElPumpo** [comment]
Yes I publiahed this beta as framework dependent which might have been a bad idea. Did you install both x86 and amd64 .NET 7 runtime?

**Comment by Ominousonion666** [comment]
Hi, local ones work, thanks! Sorry to post here again. Didn't want to create a new issue just to say this.
![image](https://user-images.githubusercontent.com/45669443/210919067-0460ff0e-5a6b-456e-b45e-e7c151e99d5f.png)

**Comment by ElPumpo** [comment]
Interesting. I will investigate. As said migrating to .NET causes new issues but they are easy to fix

**Comment by ElPumpo** [comment]
Issue has been resolved with v1.16.0. It now supports local json files with GPU metadata.

The executing driver installer issue has also been fixed. TNUC was not calling for UAC which apparently is a old bug?

Thanks for bearing with my code. Enjoy the new release everyone!
