### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by ElPumpo** [ElPumpo/TinyNvidiaUpdateChecker#143]
Error handling is really bad as we don't know if the server couldn't be contacted. Instead the code assumes that GPUs aren't in the metadata repo.

Also generally error handing needs improvements

**Comment by Pkistampally** [comment]
Thank You Samuel for this. Also  as said the orgs are blocking raw. github so please if you can have some local files where we can point them to then that would be great as well. waiting for the new version before Christmas :)
