### ISSUE TITLE
GPU Type Prompt Update

### ISSUE THREAD

**Issue by hl2guide** [ElPumpo/TinyNvidiaUpdateChecker#15]
I'd recommend that the GPU Type Selection Prompt should read as:

![screen](https://user-images.githubusercontent.com/17044982/30288314-a0ee4080-976b-11e7-95ee-150921614b29.png)

**Comment by ElPumpo** [comment]
Yes, I'd love it aswell. How about I'll add it to v1.9.0? Never did it this way because you cannot change the `Yes` and `No` inside the regular message boxes

**Comment by ElPumpo** [comment]
Now we'll assume based on the gpu name.
Example: GTX 970**M** compared to GTX 970
