### ISSUE TITLE
Nothing happens when opening 1.16.1 version

### ISSUE THREAD

**Issue by LordSimal** [ElPumpo/TinyNvidiaUpdateChecker#150]
Just downloaded the new 1.16.1 version and tried to run it but nothing is happening.

I made sure that [.NET Desktop Runtime 7 x86](https://dotnet.microsoft.com/en-us/download/dotnet/7.0) is installed.

There is like a split second where I can see a new icon appearing at the end of the task bar but it disappears immediately.

https://user-images.githubusercontent.com/9105243/213885079-d96db03a-7f07-416e-b136-43e4cf8205f7.mp4

**Comment by ElPumpo** [comment]
Hello. Well okay run it from CMD and show the results

**Comment by Nive9** [comment]
I think I might have just had a similar issue because Windows Terminal/ PowerShell suggested downloading .NET 7 from [here](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-7.0.2-windows-x86-installer?cid=getdotnetcore) (24MB;  `dotnet.microsoft.com`).

Fixed it by downloading the Offline Installer from [here](https://www.itechtics.com/net-7/#runtime) (50MB; `visualstudio.microsoft.com`).

My error was `[process exited with code 2147516566 (0x80008096)]` and it seems that the .NET 7 install wasn't properly recognised when using the Terminal-suggested link.

Not sure if this helps.

**Comment by H1deMyFace** [comment]
Hello, first, thanks for creating this app.
I have the same problem and this is my error prompt:

D:\Tiny Nvidia Update Checker>TinyNvidiaUpdateChecker.v1.16.1.exe
You must install or update .NET to run this application.

App: D:\Tiny Nvidia Update Checker\TinyNvidiaUpdateChecker.v1.16.1.exe
Architecture: x86
Framework: 'Microsoft.WindowsDesktop.App', version '7.0.0' (x86)
.NET location: C:\Program Files (x86)\dotnet\

No frameworks were found.

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.WindowsDesktop.App&framework_version=7.0.0&arch=x86&rid=win10-x86

And I have those frameworks installed.

**Comment by ElPumpo** [comment]
Yea it is strange that their info is wrong. Try https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-7.0.2-windows-x86-installer?cid=getdotnetcore

**Comment by H1deMyFace** [comment]
My Windows update downloaded this version automatically. Didn't work.

**Comment by ksbrar** [comment]
Same here, nothing happens.

**Comment by LordSimal** [comment]
```
PS C:\Users\Kevin\Desktop> .\TinyNvidiaUpdateChecker.v1.16.1.exe
You must install .NET to run this application.

App: C:\Users\Kevin\Desktop\TinyNvidiaUpdateChecker.v1.16.1.exe
Architecture: x86
App host version: 7.0.2
.NET location: Not found

Learn about runtime installation:
https://aka.ms/dotnet/app-launch-failed

Download the .NET runtime:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x86&rid=win10-x86&apphost_version=7.0.2
PS C:\Users\Kevin\Desktop>
```
I tried that download link as well, installed `aspnetcore-runtime-7.0.2-win-x86` but still the same even when executing it with powershell.

**Comment by keton** [comment]
I have same problem too dspite installing what it told me to install I'm constantly getting
```
C:\Users\keton>C:\Users\keton\TinyNvidiaUpdate\TinyNvidiaUpdateChecker.exe
You must install .NET to run this application.

App: C:\Users\keton\TinyNvidiaUpdate\TinyNvidiaUpdateChecker.exe
Architecture: x86
App host version: 7.0.2
.NET location: Not found

Learn about runtime installation:
https://aka.ms/dotnet/app-launch-failed

Download the .NET runtime:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x86&rid=win10-x86&apphost_version=7.0.2
```

**Comment by LordSimal** [comment]
Here is my `dotnet --info` output
```
PS C:\Users\Kevin\Desktop> dotnet --info

Host:
  Version:      7.0.2
  Architecture: x64
  Commit:       d037e070eb

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by ElPumpo** [comment]
Yea this is strange. You would expect Microsoft to link to the proper download but no they couldnt get it right.

So I tried on my dads computer. For him made it work with the link in the error message (shown below). I am not sure why it wouldnt be the same for everyone..

https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x86&rid=win10-x86&apphost_version=7.0.2

**Comment by LordSimal** [comment]
no, everything I installed is x64

**Comment by ElPumpo** [comment]
Yes good ideq I will clearify this. But it does say x86 in the requirements. Then Wow64 handles the magic so it can run on amd64

**Comment by LordSimal** [comment]
Yea, it does say [.NET Desktop Runtime 7 x86](https://dotnet.microsoft.com/en-us/download/dotnet/7.0) but I definitely overread the `x86` part because usually installing the x64 is enough.

**Comment by ElPumpo** [comment]
So yea make sure you installed x86. I will improve the readme

**Comment by LordSimal** [comment]
The weird part is that this is only needed since .NET version 7
Maybe you can provide separate .exe files for amd64 and x86? this would also help.

**Comment by ElPumpo** [comment]
Its not weird you need the runtime. More and more programs will require it when they migrate from .NET Framework
