### ISSUE TITLE
System . Net. Http.HttpRequestException: The requested address is not valid in its context

### ISSUE THREAD

**Issue by DoisPontinhos** [ElPumpo/TinyNvidiaUpdateChecker#152]
I'm trying TinyNvidiaUpdateChecker for the first time but I'm getting a bunch of errors. Any help ?
![image](https://user-images.githubusercontent.com/82269167/213941286-bbdc9145-d082-4edb-93ed-b8ac286600c2.png)

**Comment by DoisPontinhos** [comment]
Yes

**Comment by ElPumpo** [comment]
Okay super strange. Can you try it on another computer to see if its not your computer bring weird?

**Comment by DoisPontinhos** [comment]
Unfortunately I don't have another computer with a nvidia gpu where I can test it

**Comment by DoisPontinhos** [comment]
So I decided to try and launch the app again and it's now working xD

**Comment by ElPumpo** [comment]
Okay.. weird issue for sure but glad it works now

**Comment by harjeevan** [comment]
Hi @ElPumpo
I've been suffering from the same issue, I managed to link it to having NordVPN running whilst attempting to run the program. When disconnecting from the VPN, it runs fine.

**Comment by ElPumpo** [comment]
Sounds really weird. I cannot do anything about it this is an issue with .NET not my tool
