### ISSUE TITLE
1.16.1 being detected as Trojan still 

### ISSUE THREAD

**Issue by Dantasstic** [ElPumpo/TinyNvidiaUpdateChecker#153]
![2023-01-23 - 0008-26](https://user-images.githubusercontent.com/48727187/213983510-e74677ba-e134-4c8c-8add-c2967044552e.png)

**Comment by Dantasstic** [comment]
I have gone back to running 1.15.4 at the moment.

**Comment by ElPumpo** [comment]
Well you shouldnt always listen to Defender it's full of shit 😀

I will file a false negative on m$. But you can always allow it and run it as usual. You dont have to use the older version..

**Comment by Dantasstic** [comment]
I understand, I'm simply letting you know that despite the recent changes you made, the app is still being detected falsely.

**Comment by ElPumpo** [comment]
Yes I now get the point.

Honestly dont know what to do about it except send it to them every time I release update but their response is delayed I belive

**Comment by ElPumpo** [comment]
Reopened #131, this is a duplication issue
