### ISSUE TITLE
1.16.1 - BitDefender detect it as virus

### ISSUE THREAD

**Issue by matiastarriopages** [ElPumpo/TinyNvidiaUpdateChecker#155]
Hi,
In version 16.1 I have the following message from BitDefender Antivirus:
Detected as Gen:Variant.Lazy.274257

I downloaded version 15.4 again and it's fine, so the problem is only with the last version.

Thanks!

**Comment by ElPumpo** [comment]
Duplication of #153 I know it was about Defender but keep it in the same issue
