### ISSUE TITLE
Failure processing application bundle

### ISSUE THREAD

**Issue by similaresolsimi** [ElPumpo/TinyNvidiaUpdateChecker#156]
hi,

Thanks you for your work.

I've silent crash on a W10 with version v16.0 and v16.1.

Commande reponse is :
Failure processing application bundle.
Bundle header version compatibility check failed.
A fatal error occured while processing application bundle

it's because computer is without .NET6 installed.
https://github.com/dotnet/runtime/issues/59819

just installing and it works
https://dotnet.microsoft.com/en-us/download

tks.

Ps: 11 Mo is'nt it too fat ?

**Comment by ElPumpo** [comment]
Yes you need the runtime
