### ISSUE TITLE
Release notes without any links cause a `ArgumentNullException` when retrieving GPU information

### ISSUE THREAD

**Issue by clovdystackflow** [ElPumpo/TinyNvidiaUpdateChecker#159]
well, after the fix in 1.16, i got another error. this time its this.

![imagen](https://user-images.githubusercontent.com/100868740/214875300-2d2a2030-ad96-47a8-a337-22395919bf73.png)

**Comment by ElPumpo** [comment]
Ugh. Can you run with the `--debug` command line argument?

**Comment by clovdystackflow** [comment]
that IS the debug arg. i dont really know what you mean by showing you the gpu but here you go

![imagen](https://user-images.githubusercontent.com/100868740/214921265-2cb82fe4-3206-46d3-9785-5ff42c65d330.png)

**Comment by clovdystackflow** [comment]
[](url)

**Comment by ElPumpo** [comment]
![image](https://user-images.githubusercontent.com/12564301/214940387-3bd01079-1414-45bd-8b65-aeca1026b8c1.png)
Gotcha

**Comment by ElPumpo** [comment]
Adressed in v1.16.3. Thanks for the help.

**Comment by hubertsng** [comment]
Can you reopen this as non-complete @ElPumpo. Having the exact same issue on my fresh install of windows 11 on my rtx 3070. Installed all the .net frameworks, all the .net runetimes, all the c++ redistributables as I do on every fresh install. Windows update checks and reboots. 

Final reboot I run with --debug. 

`TinyNvidiaUpdateChecker v1.16.4

Arg: --debug

configFile: C:\Users\huber\AppData\Local\Hawaii_Beach\TinyNvidiaUpdateChecker\app.config
CHECK_UPDATE: true
MINIMAL_INSTALL: true
DOWNLOAD_LOCATION: us

Verifying internet connection . . . OK!
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'paths')
   at System.ArgumentNullException.Throw(String paramName)
   at System.IO.Path.Combine(String[] paths)
   at TinyNvidiaUpdateChecker.Handlers.LibaryHandler.EvaluateLibary()
   at TinyNvidiaUpdateChecker.MainConsole.CheckDependencies()
   at TinyNvidiaUpdateChecker.MainConsole.Main(String[] args)
`

Deleting the client version check does not fix this at all (as that's the thing that happens next in the log and same error is shot.)

**Comment by ElPumpo** [comment]
@hubertsng it is a seperate issue please open a new issue
