### ISSUE TITLE
.NET 7 error links to wrong installer

### ISSUE THREAD

**Issue by butterbutts** [ElPumpo/TinyNvidiaUpdateChecker#161]
Trying to run the program without .net 7 links to the aspnetcore 7 installer, but it seems like it actually needs the windowsdesktop installer.

**Comment by ElPumpo** [comment]
There is nothing I can do about it. I have linked the proper runtime in the readme

**Comment by R3ality** [comment]
Link in the README is correct but it could do with an added note of which variant should be downloaded since that page has many different flavors

![image](https://user-images.githubusercontent.com/762122/217189098-58e20cf8-87ab-4a32-aefb-792acced2af3.png)

**Comment by Technetium1** [comment]
Maybe the full URL should have a scroll to text fragment added to highlight which category, then picking `x86` is obvious.

**Comment by butterbutts** [comment]
Actually since the program requires Windows 10/11 to run now, there could also be a suggestion to just install the runtime through Winget. I know Windows 11 comes with winget preinstalled, and I think 10 does now too.
Something like "Follow this link or run 'winget install Microsoft.DotNet.DesktopRuntime.7 --architecture x86'"

**Comment by ElPumpo** [comment]
Good idea guys I will clearify this in the readme with a screenshot of the website.

@butterbutts cool I will add this too.

@ronen1n you 100% sure on this?

**Comment by ronen1n** [comment]
> Good idea guys I will clearify this in the readme with a screenshot of the website.
> 
> @butterbutts cool I will add this too.
> 
> @ronen1n you 100% sure on this?

I'm not sure, but it took me a lot of tries to make the new version to work, and I'm sure I installed the .net 7 x86 because I installed every version on this Microsoft download site, and it didn't work (and try to repair them too after) so I removed everything except .net 7 x86 that someone said in this post, and it still didn't work, so I remove that version too and installed again from winget

**Comment by ElPumpo** [comment]
I find it hard that old .NET runtimes would cause this compatability issue it makes no sense that Microsoft devs would let this happen

**Comment by ronen1n** [comment]
> I have two older versions of the runtime installed (aside 7 which is the requirement for TinyNvidiaUpdateChecker) and this had no negative effects.
> 
> ![image](https://user-images.githubusercontent.com/762122/219424229-6cef5bbc-8183-4898-8812-5eae70af0770.png)
> 
> This doesn't necessarily mean there is no possibility of conflicts with some other previous versions (note that my older versions are also x64 not x86) but it would probably have to be confirmed before asking users to uninstall runtimes they may need for some of their other applications.

I'm not sure what made it work maybe try to install old x86 
I tryied to install and uninstall several times and it didn't work and tried to install all versions on the website that x86 and it didn't work, only after uninstall everything and install the Winget version it worked like I said 
Maybe it was some other thing that make it not work. I have several vm's I'll try it again there and see but anyway it seems good idea too recommend if it's not working for someone.

**Comment by ronen1n** [comment]
I can't replicate this on vm, so maybe may mistake or other unknown bug.
If it appends again, ill try to record before fixing to find the real problem.

**Comment by ElPumpo** [comment]
Sounds like a broken installation of it..
