### ISSUE TITLE
Latest update is no longer opening 

### ISSUE THREAD

**Issue by diagtex** [ElPumpo/TinyNvidiaUpdateChecker#162]
Hello, 

I just grabbed V 1.16.3

When I attempt to launch it will briefly open a CMD window then auto close. I'm unsure if its able to check for Nvidia update before it closes or not. 

Tried launching from desktop, and running as admin. 

Specs:
Windows 11 | Ryzen 9 5900HS | RTX 3070 GPU | 40 GB ram

**Comment by ElPumpo** [comment]
Hi. I suspect you did not download the .NET runtime, did you?

Run TNUC from CMD and show the error

**Comment by Cjkeenan** [comment]
Make sure you download the x86 version of .NET Desktop Runtime 7.0.2 I installed the x64 version by accident first until I read the installation instructions more closely.

**Comment by SaccoSVD** [comment]
Trying to download is impossible. Edge says "Cannot download, no permissions" even if I stated twice to Keep the file.

**Comment by poeterm** [comment]
I had exactly the same problem and behavior since version 1.6.0
Also made the mistake to install .NET x64.

After installing .NET x86 everything works fine as usual again.

**Comment by ElPumpo** [comment]
@SaccoSVD can't help you if you are unable to download it 👀

**Comment by diagtex** [comment]
> Make sure you download the x86 version of .NET Desktop Runtime 7 I installed the x64 version by accident first until I read the installation instructions more closely.

Thanks for calling this out, I didn't grab the x86 installation. After it worked like a charm thank you!

**Comment by Technetium1** [comment]
@SkilledAlpaca unfortunately not, unless it's wrapped in something else. https://stackoverflow.com/questions/72597043/detect-the-absence-of-net-6-runtime-and-ask-user-to-download-net-6-runtime

**Comment by ElPumpo** [comment]
Agreed I know if you try to run a .NET Framework 3 program on Windows 10 it prompts that its runtime is missing and you can install it. But for .NET they failed this big time

**Comment by sdellenb** [comment]
I also had to uninstall the .NET 6 SDK before I could get it to work. It was always trying to load hostfxr.dll from the SDK (6.0.13).
Seems the SDK path has precedence over the runtimes.

**Comment by ElPumpo** [comment]
@sdellenb interesting this can explain theres another guy who also experienced similar issue...

**Comment by ElPumpo** [comment]
Okay updated readme to hopefully fix the confusion
