### ISSUE TITLE
GPUs without NVIDIA drivers installed are not recognized

### ISSUE THREAD

**Issue by ElPumpo** [ElPumpo/TinyNvidiaUpdateChecker#163]
If you for example DDU to do a clean install of GPU drivers then TNUC will not identify any GPU(s) as NVIDIA. This is because it uses the GPU name which is "Generic Driver" if you have no driver installed.

I have to somehow lookup the GPU name from device and vendor ID with online database. There is already public databases:

- https://pci-ids.ucw.cz/v2.2/pci.ids
- https://www.pcilookup.com/api.php?action=search&vendor=10DE&device=13C2

**Comment by ZenitH-AT** [comment]
This might work https://pci-ids.ucw.cz/v2.2/pci.ids

**Comment by ElPumpo** [comment]
Thanks for the tips. Also https://www.pcilookup.com/ has a API för this

**Comment by ElPumpo** [comment]
https://www.pcilookup.com/api.php?action=search&vendor=10DE&device=13C2

**Comment by LukeDuring** [comment]
Hey Guys, is this the same issue? I recently updated my game ready drivers through nvidia (through the standard installer), but now Tiny thinks I don't have an nvidia driver after restart? I also tried reinstalling the same driver as a 'Clean Install' option in the nvidia installer...still no luck unfortunately.

![Tiny Update](https://user-images.githubusercontent.com/93626396/222845250-82001ebf-3673-4881-bc53-83c44ed84796.png)

**Comment by olivergrosche** [comment]
same here. i didn´t even used the nvidia installer. 
last install with the older version of tiny.

**Comment by ksbrar** [comment]
+1 - same issue as @LukeDuring and @olivergrosche

**Comment by ElPumpo** [comment]
Well open seperate issues since they are not related to this one

**Comment by ElPumpo** [comment]
will be released with v1.18.0. I've done this using the PCI Lookup API. But it needs more work with proper sanitization. See issue #215
