### ISSUE TITLE
scoop download url is wrong

### ISSUE THREAD

**Issue by tastypear** [ElPumpo/TinyNvidiaUpdateChecker#166]
it should be
https://github.com/ElPumpo/TinyNvidiaUpdateChecker/releases/download/VERSION/TinyNvidiaUpdateChecker.exe
not
https://github.com/ElPumpo/TinyNvidiaUpdateChecker/releases/download/VERSION/TinyNvidiaUpdateChecker.VERSION.exe

**Comment by ElPumpo** [comment]
Correct. I knew this would break. Will file a issue on their repo

**Comment by ElPumpo** [comment]
https://github.com/ScoopInstaller/Extras/pull/10412 fix apparently on its way

**Comment by sitiom** [comment]
- Fixed in https://github.com/ScoopInstaller/Extras/pull/10491

**Comment by ElPumpo** [comment]
Hi @sitiom I have a question for you my project has over 1000 stars on GitHub can I submit it to the master Scoop repository?

Also thanks for the knowledge on pr merge

**Comment by sitiom** [comment]
No, the Main bucket does not accept GUI applications.

**Comment by ElPumpo** [comment]
Fair enough
