### ISSUE TITLE
No NVIDIA driver was found for your system configuration.  

### ISSUE THREAD

**Issue by TheOnlyKarsh** [ElPumpo/TinyNvidiaUpdateChecker#167]
![tiny](https://user-images.githubusercontent.com/69398147/218263768-303c7bb9-9dd6-4dde-9de7-460d389f6b4f.jpg)

I get this with the new update to v1.16.4.

**Comment by ElPumpo** [comment]
This is really weird, can you try to run TNUC again to see if this issue still exists?

Also can you navigate to 

https://gfwsl.geforce.com/services_toolkit/services/com/nvidia/services/AjaxDriverService.php?func=DriverManualLookup&pfid=942&osID=57&dch=1

and post your results, thanks.

**Comment by TheOnlyKarsh** [comment]
Works now.  Not sure what the issue was.

**Comment by ElPumpo** [comment]
Yea that was super weird. Will close the issue
