### ISSUE TITLE
ArgumentNullException after successfully verifying internet connection

### ISSUE THREAD

**Issue by hubertsng** [ElPumpo/TinyNvidiaUpdateChecker#168]
Having this issue on my fresh install of windows 11 on my rtx 3070. Installed all the .net frameworks, all the .net runetimes, all the c++ redistributables as I do on every fresh install. Windows update checks and reboots.

Final reboot I run with --debug.

`TinyNvidiaUpdateChecker v1.16.4

Arg: --debug

configFile: C:\Users\huber\AppData\Local\Hawaii_Beach\TinyNvidiaUpdateChecker\app.config
CHECK_UPDATE: true
MINIMAL_INSTALL: true
DOWNLOAD_LOCATION: us

Verifying internet connection . . . OK!
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'paths')
at System.ArgumentNullException.Throw(String paramName)
at System.IO.Path.Combine(String[] paths)
at TinyNvidiaUpdateChecker.Handlers.LibaryHandler.EvaluateLibary()
at TinyNvidiaUpdateChecker.MainConsole.CheckDependencies()
at TinyNvidiaUpdateChecker.MainConsole.Main(String[] args)
`

Deleting the client version check does not fix this at all (as that's the thing that happens next in the log and same error is shot.)

**Comment by ElPumpo** [comment]
This issue is something to do with libary lookups for the minimal install feature. You can disable it to make TNUC temporary work, it looks like some path was broken will investigate.

**Comment by hubertsng** [comment]
Ran this today with the same tinyupdate version on the same machine. Not sure what changed, or possibly can change other than Nvidia's lookup. Either way I was able to install the latest game ready minimal drivers. 

I'll leave this open if ElPumpo is still interested in looking at why.

**Comment by ElPumpo** [comment]
This issue is caused by the 7-zip and winrar lookups for the minimal install feature.

You have a pathing that causes an error but they should be silensed. Next update will resolve the issue, in the mean time you can change your configuration file to disable minimal install for now

**Comment by ElPumpo** [comment]
Sorry for the extreme delay @hubertsng I have not been very active in this project.

I have now released v1.16.5 which hopefulyl resolves this issue. Please test this new version and report back to verify the issue has been resolved, thanks.

**Comment by hubertsng** [comment]
> 

No worries! This is an amazing project that you opted to create and are able to take a break with life and all. I don't seem to have an issue with this. Thank you so much!
