### ISSUE TITLE
No NVIDIA driver was found for your system configuration.

### ISSUE THREAD

**Issue by Kruschak** [ElPumpo/TinyNvidiaUpdateChecker#169]
Hey,
with the current version i get the following output:

TinyNvidiaUpdateChecker v1.16.4

Verifying internet connection . . . OK!

Searching for Updates . . . OK!

Retrieving GPU information . . . ERROR!
No NVIDIA driver was found for your system configuration.

gpuId:       877
osId:        57
isDchDriver: 1

Before i was using an much older version (around 2-4 months) which worked fine for me. 
I have an RTX 2080 TI and im using Windows 10 64 bit. The pfid and osID are correct.

This is the generated URL from 1.16.4 which results to 0 results
https://gfwsl.geforce.com/services_toolkit/services/com/nvidia/services/AjaxDriverService.php?func=DriverManualLookup&pfid=877&osID=57&dch=1

This results in 0 Results:
{ "Success" : "0", "IDS" : [{ "downloadInfo": { "Success" : "0", "ID" : "", "Messaging" : [{"MessageCode" : "DriverDownloadIDNotFound", "MessageValue" : "The Driver Download not found for Manual Lookup requested"}]}}],"spcall" : "EXEC NDL_usp_Download_select_by_matrix_values null,877,null,null,57,null,0, null,null,1,null,0,null,null,null,null,1,null,null,null,null,1,null,0,0,null,null,null,null,null,null,null,null,null,null,null,null,null,1,null", "Request" : [{"psid" : "null", "pfid" : "877", "osID" : "57", "languageCode" : "null", "beta" : "0", "isWHQL" : "1", "dltype" : "1", "sort1" : "null", "numberOfResults" : "1"}]}

Reporting this to support your work. Thanks for the great project.

**Comment by ElPumpo** [comment]
Hi and thanks for the kind words. It's not the first time NVIDIA response is no driver found. When I open your link I get a complete different response. Driver was found.

Dont know why this happens but it's nothing I can change..

**Comment by Kruschak** [comment]
Can confirm the issue is now gone without anything changed on our side. The link is now working again and the tool also is working again.
So it was an issue on the Nvidia side which is now gone.
Thanks and keep the good work up.
