### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by molagbaal38** [ElPumpo/TinyNvidiaUpdateChecker#170]
Good morning,

sorry for my english, i'm french and i use google translate.

I have been using tiny nvidia for a long time without ever changing versions, now I just changed graphics cards I updated tiny to the latest version,

I followed the tutorial
*install net.x86
*uninstall the drivers/geforce with the DDU software

then tiny starts fine but with this error:
*inernet connection:ok
*retrieving gpu information:error
*"no supported nvidia gpu was found! if you have a nvidia gpu then manually install a driver for it first, then use tnuc to keep it updated."
Can you help me please

**Comment by ElPumpo** [comment]
Hi. Can you show a screenshot of your GPU in device manager?

**Comment by molagbaal38** [comment]
> Salut. Pouvez-vous montrer une capture d'écran de votre GPU dans le gestionnaire de périphériques ?
> 
> Oh oui, si vous exécutez DDU, TNUC pourra identifier votre GPU en tant que produit NVIDIA. Reportez-vous au [numéro 163](https://github.com/ElPumpo/TinyNvidiaUpdateChecker/issues/163)
Hi and thank you for your reply,

I had to reinstall the nvidia driver with gerforce to get tiny to work again.

I read message #163 but I have trouble translating, I don't really understand what I have to do if I remove the nvidia driver to make tiny work.

could you explain to me please?
thanks

**Comment by ElPumpo** [comment]
Duplication of #163 . Closing issue

**Comment by molagbaal38** [comment]
ok i will wait for a fix then

**Comment by ElPumpo** [comment]
No worries. My tool requires driver to be installed already
