### ISSUE TITLE
Migrate from x86 to x64

### ISSUE THREAD

**Issue by bingis-khan** [ElPumpo/TinyNvidiaUpdateChecker#171]
Is this possible? Why not? 

Ideally it would simplify the installation, since all you'd need is Scoop (and avoiding yet another dotnet runtime means less bloat/cringe).

**Comment by ElPumpo** [comment]
What? My project is built for x86 to work for more systems. Windows does not ship with .NET 7 runtime either

**Comment by ZhangTianrong** [comment]
It seems that x86 dotnet7 is no longer supported on Windows 11 according to [this](https://learn.microsoft.com/en-us/dotnet/core/install/windows?tabs=net70#dependencies). Is there a way to install the x86 runtime?

**Comment by RichardLuo0** [comment]
> What? My project is built for x86 to work for more systems. Windows does not ship with .NET 7 runtime either

Hi, could you release two versions, one for x64 and one for x86? I simply don't want to install another runtime on my computer. PS: You may consider using GitHub actions to automatically build your project, shouldn't be very difficult.

**Comment by ElPumpo** [comment]
Hi Richard.

As I previously have mentioned I don't want to. It feels overcomplicated to release two executables. For me it makes no sense either.

You dont want to install a library that makes my code run on most systems. No.

Hopefully you understand

**Comment by ElPumpo** [comment]
I am revisiting this, I believe a move to x64 is due. It has been asked by many, and x86 drivers are very outdated/not supported by TNUC anyways
