### ISSUE TITLE
TinyNvidiaUpdateChecker doesn't work with any of the .net 7

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [ElPumpo/TinyNvidiaUpdateChecker#173]
I tried from 7.0 up to 7.0.3, the sdk, the runtime and the windows-runtime, separately. On Windows Sandbox. Every time I'm getting this error no matter what I do:

![image](https://user-images.githubusercontent.com/3938423/224472696-f22f7bf1-2633-4ac3-8594-9b071cb63bdd.png)

**Comment by Unrepentant-Atheist** [comment]
Alright, apparently I need the x86 version of .net 7 too. My bad..

**Comment by ElPumpo** [comment]
Yee I will improve the requirements soonTM to make it more clear
