### ISSUE TITLE
Getting "Your current GPU driver is newer than what NVIDIA reports!"

### ISSUE THREAD

**Issue by aricd** [ElPumpo/TinyNvidiaUpdateChecker#175]
Executing `tinynvidiaupdatechecker.exe` shows:
```
TinyNvidiaUpdateChecker v1.16.4

Generating configuration file.

Verifying internet connection . . . OK!

Searching for Updates . . . OK!

Retrieving GPU information . . . OK!
Your current GPU driver is newer than what NVIDIA reports!

Press any key to exit...
```

Executing `nvidia-smi.exe` shows:
```
Tue Mar 28 10:30:04 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 531.29                 Driver Version: 531.29       CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                      TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Quadro RTX 5000               WDDM | 00000000:01:00.0  On |                  Off |
| 34%   32C    P8               16W / 230W|    920MiB / 16384MiB |      2%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
```

I was expecting an install of 531.41, over my 531.29.  Not sure what's happening here.  Is there a log so can I see what the software thinks my driver version is?

**Comment by ElPumpo** [comment]
Hi well yea that is weird. Can you run TNUC with the `--debug` arg?

Can you show your GPU in device manager? Desktop or laptop? And where did you download your driver from?

**Comment by aricd** [comment]
Running with `--debug` I get: 

```
TinyNvidiaUpdateChecker v1.16.4

Arg: --debug

configFile: C:\Users\UserName\AppData\Local\Hawaii_Beach\TinyNvidiaUpdateChecker\app.config
CHECK_UPDATE: true
MINIMAL_INSTALL: true
DOWNLOAD_LOCATION: us

Verifying internet connection . . . OK!

Searching for Updates . . . OK!
offlineVer: 1.16.4
onlineVer:  1.16.4

Retrieving GPU information . . . OK!
downloadURL: https://us.download.nvidia.com/Windows/Quadro_Certified/528.89/528.89-quadro-rtx-desktop-notebook-win10-win11-64bit-international-dch-whql.exe
pdfURL:      https://us.download.nvidia.com/Windows/Quadro_Certified/528.89/528.89-win10-win11-nvidia-rtx-quadro-release-notes.pdf
releaseDate: 3/30/2023
downloadFileSize:  663 MiB
OfflineGPUVersion: 531.29
OnlineGPUVersion:  528.89
Your current GPU driver is newer than what NVIDIA reports!

Press any key to exit...
```

Yes, with OfflineGPUVersion: 531.29 and OnlineGPUVersion:  528.89 my driver is newer.

I have a desktop with a Quadro RTX 5000.  My previous driver install was from "531.29-notebook-win10-win11-64bit-international-dch-whql.exe" downloaded from here: https://www.nvidia.com/download/index.aspx.  I realize that previously I didn't bother choosing "Nvidia RTX / Quatro" at the first step of download page, and got the more common non-enterprise driver.

It appears that TNUC chooses the "Production Branch/Studio" driver option for my card, not the "New Feature Branch (NFB)" or "Quadro New Feature (QNF)" option.  

From the standard Nvidia download page when choosing: 
- NVIDIA RTX Quadro
- NVIDIA RTX Series
- NVIDIA RTX A5000
- Windows 10 64-bit
- **New Feature Branch**
- English (US)

the recommended driver file name is: 531.41-quadro-rtx-desktop-notebook-win10-win11-64bit-international-dch-whql.exe which is the version that I want.  Is there a way to configure the software to get this result?

**Comment by ElPumpo** [comment]
@ZenitH-AT welp

**Comment by ZenitH-AT** [comment]
The newer driver version shows up if you add `isWHQL=0` to the URL parameters as shown [here](https://gfwsl.geforce.com/services_toolkit/services/com/nvidia/services/AjaxDriverService.php?func=DriverManualLookup&pfid=943&osID=57&dch=1&isWHQL=0).

Perhaps "New Feature Branch" just means non-WHQL certified drivers are included?

It may be worth supporting non WHQL verified drivers (isWHQL parameter) with some options. The same probably applies to the "beta=1" parameter.

**Comment by aricd** [comment]
Thank you, this helped me understand what's happening.

**Comment by ElPumpo** [comment]
Well you didnt have to close the issue but yea now you know why this happens..
