### ISSUE TITLE
cant make last version working

### ISSUE THREAD

**Issue by zdhar** [ElPumpo/TinyNvidiaUpdateChecker#176]
hi
i cant make the last version working
here is what it says :

"D:\Program Files\TinyNvidiaUpdateChecker-1.16.4>TinyNvidiaUpdateChecker
You must install .NET to run this application.

App: D:\Program Files\TinyNvidiaUpdateChecker-1.16.4\TinyNvidiaUpdateChecker.exe
Architecture: x86
App host version: 7.0.2
.NET location: Not found

Learn about runtime installation:
https://aka.ms/dotnet/app-launch-failed

Download the .NET runtime:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x86&rid=win10-x86&apphost_version=7.0.2"

i downloaded everything on this page  in 7.0.5 and 7.0.2 too, same results 

ty for your help

**Comment by zdhar** [comment]
ok solved following last post
winget install Microsoft.DotNet.HostingBundle.7 then downloaded https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-7.0.5-windows-x86-installer?cid=getdotnetcore

**Comment by ElPumpo** [comment]
Hi, as discussed in #161 and #162 you need the desktop runtime x86. Improved readme is coming aswell to clearify
