### ISSUE TITLE
Always searches updates for computing card Tesla M40 instead of 1080 Ti

### ISSUE THREAD

**Issue by Tom-Neverwinter** [ElPumpo/TinyNvidiaUpdateChecker#177]
gpu name: Tesla M40
is Notebook: false

these are almost never the primary card though. this is for a ai project. [may need code to select main gpu over seconday]

**Comment by ElPumpo** [comment]
Hi, can you please show all your GPUs in a device manager screenshot?

@ZenitH-AT 👀

**Comment by ElPumpo** [comment]
Uuum okay yea I belive with multiple GPUs my needs to identify this and make you able to choose which one.

Currently I belive the code just chooses the first regex match, I take it your main GPU is 1080 Ti? But does the Tesla cards not receive frequent driver updates aswell?

**Comment by ElPumpo** [comment]
So I assume you want to use TNUC to check drivers for your 1080 Ti card?

TNUC needs proper logic for multiple card handling. For example one like in this case computing cards that should be ignored, and instead search for the next GPU if it's a GTX/RTX/Whatever.

**Comment by ElPumpo** [comment]
Hi sorry for the extreme delay, v1.18.0 will be released with an fix to this issue.
![image](https://github.com/ElPumpo/TinyNvidiaUpdateChecker/assets/12564301/96de7712-c03c-4275-ae58-ea56a8401a65)

**Comment by ElPumpo** [comment]
Thanks for the quick @Tom-Neverwinter . In fact the update was just released. Please try the new version out and report back.

**Comment by ElPumpo** [comment]
No it's not a runtime error it would never run if that was the case. Other users have the same issue I need to investigate

**Comment by ElPumpo** [comment]
That bug is fixed in the newest release

**Comment by ElPumpo** [comment]
Ok cool! New release coming
