### ISSUE TITLE
option to re-install current driver

### ISSUE THREAD

**Issue by sam0x17** [ElPumpo/TinyNvidiaUpdateChecker#178]
Users of e-gpus on win11 often need to re-install the current nvidia driver as part of the flow for getting windows to adapt to the e-gpu being connected (or not). My husband's flow right now is to disable the laptop's discrete GPU in the device manager and then run GeForce Experience to re-install the current nvidia driver. Once he does this, the e-gpu always works (albeit with some occasional blue screens). He would love to use TinyNvidiaUpdateChecker to re-install the nvidia driver instead, but when it runs, it does not think it needs to re-install and just exits. Maybe if there was some command line option to re-install the current driver?

**Comment by ElPumpo** [comment]
Hi. You can choose to force the "update available" prompt with the `--force-dl` command line argument.

Also warning if you have several NVIDIA GPUs in your system TNUC will choose the first one it finds, and search drivers for that one.

**Comment by sam0x17** [comment]
awesome ty!
