### ISSUE TITLE
Option to make it run in the SYSTRAY

### ISSUE THREAD

**Issue by berserkwarwolf** [ElPumpo/TinyNvidiaUpdateChecker#18]
I would like it to perform **daily** Driver Update Checks in the **background**, without popping up the command console. It would be nice if there was an option to enable this. I don't want to manually check for updates.

**Comment by ElPumpo** [comment]
This is already possible! 

1. put the executable somewhere (TinyNvidiaUpdateChecker)
2. make a shortcut of it
3. put the shortcut in **Run** > **shell:startup**
4. open the properties for the shortcut and add the command line argument `--quiet`
