### ISSUE TITLE
Minimal install doesnt work if 7-zip not detected

### ISSUE THREAD

**Issue by andyjf0** [ElPumpo/TinyNvidiaUpdateChecker#180]
The driver is no longer extracts after download. Reinstalling 7-zip does not fix?

**Comment by ElPumpo** [comment]
Hi Andy. If you at one point had 7-zip installed and have minimal install enabled. Once you uninstall it and run TNUC it will detect that no 7-zip is installed and disables the feature.

You can re-enable it by editing the configuration file. Which is located at `%localappdata%\Hawaii_Beach\TinyNvidiaUpdateChecker\app.config`

Edit

`<add key="Minimal install" value="false" />`

To

`<add key="Minimal install" value="true" />`

**Comment by andyjf0** [comment]
Cheers mate, that's just what I was after.

Apologise for double posting I wasn't sure where was appropriate.

Love your work!

**Comment by ElPumpo** [comment]
Thanks and no worries!
