### ISSUE TITLE
Does nothing after version 1.15.4.

### ISSUE THREAD

**Issue by Serpens66** [ElPumpo/TinyNvidiaUpdateChecker#185]
I used this in the past fine.
The version v1.14.6 did not find a new driver version, although there is for sure one.

It told me there is a new version of TinyNvidiaUpdateChecker , so I updated to newest. But when I start that exe nothing happens. Or at least nothing I can really see. The console opens for less then half a second and nothing more.
I tested all latest version: All versions with the ~1MB size dont work for me. The newest version that worked was 1.15.4.

Why does the old version v1.14.6 does not find the driver updates which are found by 1.15.4? And why are newest UpdateChecker version not working?

I'm on Windows10 Pro 64 bit.

**Comment by Serpens66** [comment]
ok, I did not notice that it now requires NET.
After doing "winget install Microsoft.DotNet.DesktopRuntime.7 --architecture x86" it works now.

**Comment by ElPumpo** [comment]
Yup. As I've said to others, it's sad they couldn't implement a dialog saying "you are missing the runtime" like they did with .NET framework 3.5
