### ISSUE TITLE
TNUC shows Studio Driver as latest driver available and no opt-out available

### ISSUE THREAD

**Issue by ejams1** [ElPumpo/TinyNvidiaUpdateChecker#187]
Just curious about this as I've used the tool for quite some time now but saw that today I got a studio driver update and not the game ready one like normal. Is that expected? I couldn't find anything specific about the matter in the docs. Thanks!
![screenshot](https://github.com/ElPumpo/TinyNvidiaUpdateChecker/assets/140560379/5b41457a-412f-4623-a203-69b48e70eff5)

**Comment by ElPumpo** [comment]
Hi thanks for the report. This is interesting. I have never seen this API return studio drivers perhaps they implemented support.

@ZenitH-AT

**Comment by ElPumpo** [comment]
@ejams1 can you run TNUC with the `--debug` command line argument and post the console here?

**Comment by ejams1** [comment]
Yep, here you go:
```
PS C:\Program Files\NVIDIA Corporation> .\TinyNvidiaUpdateChecker.exe --debug
TinyNvidiaUpdateChecker v1.16.5

Arg: --debug

configFile: C:\Users\User\AppData\Local\Hawaii_Beach\TinyNvidiaUpdateChecker\app.config
CHECK_UPDATE: true
MINIMAL_INSTALL: true
DOWNLOAD_LOCATION: us

Verifying internet connection . . . OK!

Searching for Updates . . . OK!
offlineVer: 1.16.5
onlineVer:  1.16.5

Retrieving GPU information . . . OK!
downloadURL: https://us.download.nvidia.com/Windows/536.99/536.99-desktop-win10-win11-64bit-international-nsd-dch-whql.exe
pdfURL:      https://us.download.nvidia.com/Windows/536.99/536.99-win10-win11-nsd-release-notes.pdf
releaseDate: 2023-08-08
downloadFileSize:  645 MiB
OfflineGPUVersion: 536.99
OnlineGPUVersion:  536.99
There is no new GPU driver available, you are up to date.

Press any key to exit...
```

**Comment by ejams1** [comment]
Is the `nsd` short for Nvidia studio driver I wonder?

**Comment by ElPumpo** [comment]
TNUC taps into the [NVIDIA AJAX API](https://gfwsl.geforce.com/services_toolkit/services/com/nvidia/services/AjaxDriverService.php?func=DriverManualLookup) that is developed for GF Experience.

There's no official documentation on the API, and public research is very little.

Seems like they recently added studio drivers which is good, but I don't know what parameter it is. How to filter for it / filter it out.

In that case TNUC could offer you to choose what type of driver you want. Studio drivers are for creators, you can google about it. Regulars would want game ready drivers.

**Comment by ElPumpo** [comment]
Well I did some research and finally found a `upCRD=1` parameter. If you don't have it in your request then NVIDIA will apparently choose the one most up to date?

- `1` is studio driver
- `0` is game ready

Also the AJAX response shows your request. It has `theUserRequestedCRD` which is set to `null` if you don't use the parameter.

`https://gfwsl.geforce.com/services_toolkit/services/com/nvidia/services/AjaxDriverService.php?func=DriverManualLookup&pfid=999&osID=57&dch=1&upCRD=1`

`https://gfwsl.geforce.com/services_toolkit/services/com/nvidia/services/AjaxDriverService.php?func=DriverManualLookup&pfid=999&osID=57&dch=1&upCRD=0`

**Comment by ejams1** [comment]
Great find! I have an RTX 3080 if that is still of interest

**Comment by ElPumpo** [comment]
@ejams1 thanks for the information. I will implement a opt-in for studio drivers soonTM.

**Comment by ElPumpo** [comment]
![image](https://github.com/ElPumpo/TinyNvidiaUpdateChecker/assets/12564301/c055d1f7-fe30-41d3-8176-c4ec987943dc)

**Comment by ElPumpo** [comment]
Added in v1.17.0
