### ISSUE TITLE
Disable "Press any key to exit..." with command line argument `--noprompt`

### ISSUE THREAD

**Issue by TomKranenburg** [ElPumpo/TinyNvidiaUpdateChecker#188]
Hello there, love this tiny little app. Very effective.

My one problem is that the "Press any key to exit..." prompt halts any scripts you include this in which hampers things a bit. Would it be possible to have the option to disable this with a command line argument?

I've looked into the code and I could include it myself. Should I open a pull request with it or is this something you'd want to do?

Again very nice little app. I use it often.

**Comment by TomKranenburg** [comment]
Alright I just went ahead and opened a pull request. See what you think:

https://github.com/ElPumpo/TinyNvidiaUpdateChecker/pull/189

**Comment by ElPumpo** [comment]
Replied in PR. Very good idea

**Comment by ElPumpo** [comment]
Will be released in the next update! Thanks for the help
