### ISSUE TITLE
"Quiet" command-line parameter isn't quiet enough

### ISSUE THREAD

**Issue by seagull** [ElPumpo/TinyNvidiaUpdateChecker#19]
1. Run "TinyNvidiaUpdateChecker.v1.8.0.exe --quiet --force-dl"
2. Dialogue box appears

I had been planning on using this software with a piece of RMM software that runs programs silently in the background. It would be great to be able to report on out-of-date drivers and automatically update them.
Due to the presence of a dialogue box, however, the program cannot be considered to be running silently and thus cannot be used.

Please consider either making the --quiet switch operate silently or introducing a --silent switch that auto-presumes a Y answer.

**Comment by ElPumpo** [comment]
Thanks for the feedback! What about `--install` which will install the drivers?

**Comment by seagull** [comment]
My pleasure, thanks for being so receptive.
If we're discussing wording, I'd propose `--force-install` to make it clear that user input will not be prompted.
Will this work in tandem with `--quiet` or does the setting imply interaction-free operation?

**Comment by ElPumpo** [comment]
`--force-install` is just wrong. We don't want to force an install?

**Comment by seagull** [comment]
If you don't feel so. How about "--confirm"?

**Comment by ElPumpo** [comment]
How about `--confirm-dl`

**Comment by seagull** [comment]
Yeah, that works

**Comment by Quozzo** [comment]
I was just about to suggest the same, well an auto-close option since I just threw a shortcut into the startup folder. Pressing any key is not as bad as having Geforce Experience installed on my system.

**Comment by ElPumpo** [comment]
But then how about self-updating?

**Comment by Quozzo** [comment]
I don't mind self updating. Isn't the whole point of it to update drivers? That what I want regardless of any user input.

**Comment by seagull** [comment]
From my POV the program's main use will be to give my customers as a way to inform them that their devices need a driver update. Some will use the "just install it" feature, others won't.

**Comment by ElPumpo** [comment]
With self-updating I mean updates to the application.

**Comment by seagull** [comment]
Oh, I see.
For me, just putting the text "An update is available, grab it at www.blah.xyz" in the StdOut as part of the normal program run would be sufficient.

**Comment by ElPumpo** [comment]
But you wanted everything to be automatic? Dialogs or not?

**Comment by seagull** [comment]
For me, what's important is that it runs without user input. Input is considered before the program is run as part of the arguments it's run with. If there's a "quiet" command-line (or an analogue, as we're doing here), it needs to be just that.

If you're asking me what we should do in regards to program updates, I'm perfectly fine with just saying "A new version is available" in the StdOut. That way the administrator can update their package and run the new version as behoves them. I lean against automatic updates, not least because Administrators typically prefer to keep strict inventories of every program they're using and the version number, but also because it saves you the hassle of coding anything new.

Alternatively, updating really isn't an issue to begin with for me. @Quozzo might disagree, but it seems like a new issue for a new case. As far as I'm concerned it's a non-issue and it doesn't need any additional attention.

**Comment by ElPumpo** [comment]
Ok man

**Comment by ElPumpo** [comment]
Since you're the one wanting this feature, is making a minimal install important to you?

**Comment by seagull** [comment]
Hi;
UAC isn't an issue, the software I work with runs everything in the highest user context.
Installation is undesired; the virtue of the program is its portability. An installer would be a nice extra for other people who aren't me, but if we're focusing on just my use case, I'll go for portable 100% of the time.

**Comment by ElPumpo** [comment]
> Installation is undesired; the virtue of the program is its portability. An installer would be a nice extra for other people who aren't me, but if we're focusing on just my use case, I'll go for portable 100% of the time.

I didn't mean installing TNUC? I meant using the 'minimal installer' feature, which will extract the base drivers, so that you don't install all the other shit (telemetry, extra services etc)

**Comment by seagull** [comment]
Oh, I see.
It would be great if we had some facility to just install the NVIDIA drivers, yeah, without any concern paid to GeForce Experience, HDMI audio, 3D vision, PhysX, ShadowPlay, etc., etc., etc.

**Comment by ElPumpo** [comment]
[TinyNvidiaUpdateChecker v1.9.0-beta 2.zip](https://github.com/ElPumpo/TinyNvidiaUpdateChecker/files/1315805/TinyNvidiaUpdateChecker.v1.9.0-beta.2.zip)

beta 2:
- supports portable 7zip (17.01 tested), the directory must be in the same directory and named `7-Zip` Make sure you have all the binaries! Especially `7zG.exe` and `7z.exe` are important!
- `--confirm-dl` argument that will download and install drivers automaticly, saves the installer at `%temp\*driver_version*%`

**Comment by seagull** [comment]
Thanks!
Two things:
- The `--quiet` switch still causes a prompt, which means it isn't quiet by definition. It should just say "There is an update available to version x.xx" or "There is no update available" in the StdOut.
- Running the program normally produces the following error for me:
`Retrieving GPU information . . . OK!
System.NullReferenceException: Object reference not set to an instance of an object.
at TinyNvidiaUpdateChecker.MainConsole.Main(String[] args)`

**Comment by ElPumpo** [comment]
Use `--quiet` **with** `--confirm-dl`

**Comment by ElPumpo** [comment]
For the crash, run the app with `--debug` whitch will tell us more about the problem

**Comment by ElPumpo** [comment]
@seagull try [TinyNvidiaUpdateChecker v1.9.0-beta 3.zip](https://github.com/ElPumpo/TinyNvidiaUpdateChecker/files/1326038/TinyNvidiaUpdateChecker.v1.9.0-beta.3.zip) which should give us more information about your problem. this version also comes with the new dialog for new driver 🔨 and please use the `--debug` argument and paste everything here

**Comment by Quozzo** [comment]
TinyNvidiaUpdateChecker v1.9.0 dev build

Copyright (C) 2016-2017 Hawaii_Beach
This program comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions. Licensed under GPLv3.

Arg: --debug

configFile: C:\Users\Quozzo\AppData\Local\Hawaii_Beach\TinyNvidiaUpdateChecker\app.config

Searching for a network connection . . . OK!

winVer: 10
osID:   57
verOrg: 10.0.15063.0

langID:   2
cultName: en-GB

Searching for Updates . . . OK!
offlineVer: 1.9.0
onlineVer:  1.8.0

Retrieving GPU information . . . OK!
gpuURL:      http://www.nvidia.com/Download/processDriver.aspx?psid=98&pfid=756&rpf=1&osid=57&lid=2&ctk=0
processURL:  http://www.nvidia.co.uk/download/driverResults.aspx/124420/en-uk
confirmURL:  http://www.nvidia.com/content/DriverDownload-March2009/confirmation.php?url=/Windows/385.69/385.69-desktop-win10-64bit-international-whql.exe&lang=uk&type=GeForce
downloadURL: http://uk.download.nvidia.com/Windows/385.69/385.69-desktop-win10-64bit-international-whql.exe
pdfURL:      http://uk.download.nvidia.com/Windows/385.69/385.69-win10-win8-win7-desktop-release-notes.pdf
releaseDate: 21/09/2017
OfflineGPUVersion: 385.41
OnlineGPUVersion:  385.69
There are new drivers available to download!

Making installer . . .
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at TinyNvidiaUpdateChecker.MainConsole.MakeInstaller(Boolean silent)
   at TinyNvidiaUpdateChecker.MainConsole.DownloadDriverQuiet()
   at TinyNvidiaUpdateChecker.MainConsole.DownloadDriver()
   at TinyNvidiaUpdateChecker.MainConsole.Main(String[] args)

That's what I get with v1.9.0 linked above

**Comment by ElPumpo** [comment]
@Quozzo are you using 7-Zip or WinRAR? Try [TinyNvidiaUpdateChecker v1.9.0-beta 4.zip](https://github.com/ElPumpo/TinyNvidiaUpdateChecker/files/1326508/TinyNvidiaUpdateChecker.v1.9.0-beta.4.zip) which tries to sorround the `MakeInstaller()` method with try / catch

**Comment by Quozzo** [comment]
I'm using winzip since I don't have winrar installed XD After installing WinRAR no diver was installed and I got this.

TinyNvidiaUpdateChecker v1.9.0 dev build

Copyright (C) 2016-2017 Hawaii_Beach
This program comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions. Licensed under GPLv3.

Arg: --debug

configFile: C:\Users\Quozzo\AppData\Local\Hawaii_Beach\TinyNvidiaUpdateChecker\app.config

Searching for a network connection . . . OK!

winVer: 10
osID:   57
verOrg: 10.0.15063.0

langID:   2
cultName: en-GB

Searching for Updates . . . OK!
offlineVer: 1.9.0
onlineVer:  1.8.0

Retrieving GPU information . . . OK!
gpuURL:      http://www.nvidia.com/Download/processDriver.aspx?psid=98&pfid=756&rpf=1&osid=57&lid=2&ctk=0
processURL:  http://www.nvidia.co.uk/download/driverResults.aspx/124420/en-uk
confirmURL:  http://www.nvidia.com/content/DriverDownload-March2009/confirmation.php?url=/Windows/385.69/385.69-desktop-win10-64bit-international-whql.exe&lang=uk&type=GeForce
downloadURL: http://uk.download.nvidia.com/Windows/385.69/385.69-desktop-win10-64bit-international-whql.exe
pdfURL:      http://uk.download.nvidia.com/Windows/385.69/385.69-win10-win8-win7-desktop-release-notes.pdf
releaseDate: 21/09/2017
OfflineGPUVersion: 385.41
OnlineGPUVersion:  385.69
There are new drivers available to download!

Making installer . . . OK!
Running installer . . . Could not run driver installer!


Job done! Press any key to exit.


It may be due to cancelling the download since the error only occured when clicking install and not download.

**Comment by ElPumpo** [comment]
@Quozzo yes this is my bad, I'm currently implementing a file size check for the driver file, because it skips the download if a file named (in this case) `385.69-desktop-win10-64bit-international-whql.exe`. You used the `Download + Install` button, right? In the meantime you can head over to `%temp%` and erase the `385.69` folder

**Comment by Quozzo** [comment]
Yeah that did it. So was it caused by using WinZip instead of WinRAR?

**Comment by ElPumpo** [comment]
@Quozzo please continue in #21 as your issue has nothing to do with this.

**Comment by ElPumpo** [comment]
@seagull i've closed this issue and released v1.9.0. There's now `--config-here` which uses the working directory as path for config, and `--confirm-dl` will now automaticly write the config if needed.
