### ISSUE TITLE
Optimize gpu-data.json and os-data.json fetching

### ISSUE THREAD

**Issue by wangcheng** [ElPumpo/TinyNvidiaUpdateChecker#195]
Currently TNUC will fetch the latest `gpu-data.json` and `os-data.json` every time, which is not ideal for the following reasons:
- User's GPU and OS are not changing frequently. We are wasting network resources and time to fetch them every time.
- Users in China have difficulty accessing GitHub's "raw" resources due to the GFW. Some users have proxy tools to work around the GFW but they are usually browser-based because it is tricky to enable proxy for CLI tools like TNUC.

My proposed solution:
- Currently TNUC can read local json files from working directory (usually users home dir). I think the better solution is to read them from the app config directory (`AppData\Local\Hawaii_Beach\TinyNvidiaUpdateChecker`). This will allow the user that can't access GitHub to fetch a local copy from the browser and save them in the app's own dir instead of home dir.
- To save network requests and time, we can fetch and store these 2 files locally and only fetch the latest version if we can't find the current GPU or OS in the local file.

**Comment by ElPumpo** [comment]
Hi Wang. Thanks for enlightning me about this, I agree it should be cached in the configuration directory.

You could also compare the date of the cached files so if they are a week old then update them.

Great idea! I will implement this for the next release.

**Comment by wangcheng** [comment]
Thanks for the reply!

Please consider implementing reading files from AppData folder. I will appreciated it as a user in China and I don't like the idea of put some json files in my home directory. Thanks!

**Comment by ElPumpo** [comment]
Hi sorry for the extreme delay, this feature has now been developed and will be released in the v1.18.0 update. Thank you for your feedback, indeed the implementation was very bad.

**Comment by wangcheng** [comment]
Thank you so much!
