### ISSUE TITLE
Check, if driver already is in folder XY

### ISSUE THREAD

**Issue by o0Julia0o** [ElPumpo/TinyNvidiaUpdateChecker#196]
please make a check with a userdefined folder(f.e. a network-folder) if the driver is already downloaded. So on more then 1 pc you havent to download the driver over and over again.

A local backup-folder, if driver is not in the f.e. network-folder would be good. So that the driver will be downloaded again in the local folder if the network-folder is not reachable at the moment.

**Comment by ElPumpo** [comment]
You had previouslly requested this and the answer is no.
