### ISSUE TITLE
Questions about TNUC

### ISSUE THREAD

**Issue by o0Julia0o** [ElPumpo/TinyNvidiaUpdateChecker#197]
--quiet --config-here --force-dl ?

Can you complete quielty install a driver without the nvivia-menu popping up?

can you define dl-folder in a optionsfile next to the exe?

can you let do the work without an comman-window? An task-item near the window clocl could be handy whilst doing the update stuff.

can you define only install if newer driver is available and only reinstall physicsdrver if a new version is available(but otherwise keep the actual one)?

**Comment by ElPumpo** [comment]
Hi.

You mean [Command Line Arguments, see on the wiki page](https://github.com/ElPumpo/TinyNvidiaUpdateChecker/wiki/Command-Line-Arguments).

> Can you complete quielty install a driver without the nvivia-menu popping up?

no and I have answered why in that issue you created

> can you define dl-folder in a optionsfile next to the exe?

It depends, if you download with `--quiet` then no. When prompted you can choose "Download Only" where you choose download directory in dialog

> can you let do the work without an comman-window? An task-item near the window clocl could be handy whilst doing the update stuff.

Not sure what you mean but you can setup TNUC to run on example user login, and use the --quiet argument to update automaticly

> can you define only install if newer driver is available and only reinstall physicsdrver if a new version is available(but otherwise keep the actual one)?

TNUC only prompts to update if an update is available. If you are on the latest version and TNUC still claims an update is available then it's a bug. Which you already have opened a seperate issue for.

Hope this answers your questions.
