### ISSUE TITLE
Always telling: there is a new driver available

### ISSUE THREAD

**Issue by o0Julia0o** [ElPumpo/TinyNvidiaUpdateChecker#199]
but the driver is already downloaded + extracted + installed.

Win10

**Comment by ElPumpo** [comment]
Hi. This is strange. Please run TNUC with the `--debug` and show the full output of the console.

Also show your GPU in device manager and its current version. Is your computer and GPU desktop or laptop? Or both?

**Comment by ElPumpo** [comment]
@o0Julia0o hello?
