### ISSUE TITLE
Implement WMI chassis checks to automate graphics card type detection

### ISSUE THREAD

**Issue by seagull** [ElPumpo/TinyNvidiaUpdateChecker#20]
Currently the program requires the user to state whether the Nvidia card in use is a Desktop-sized or Mobility variant. This can be automated using a basic WMI check.

In CMD, you could use the WMIC tool and the following command:
`wmic systemenclosure get chassistypes`
Compare this to a lookup table located here: https://technet.microsoft.com/en-us/library/ee156537.aspx
And you can easily tell whether a device is a Laptop or a Workstation.
My ASUS ROG Laptop, for example, identifies as {10} (notebook).

This would ideally work in tandem with my other request -- a "--silent" switch -- to completely automate Nvidia update checks, even on devices on which the software has not been previously run.

**Comment by ElPumpo** [comment]
Thanks yet again for the feedback! I'll automate it, I was too lazy at the time I implememted it.

I can implement `--auto-config` which automaticly setup the settings! But then how about client updates..? I'll may have to implement a self-updater?

**Comment by seagull** [comment]
Thanks for hearing me out.
Can I ask what you mean by client updates? Personally, I'd calculate the device's chassisType via the WMI upon each execution, as this removes the need to store anything locally (ideally, there would be no need for anything to be stored in /AppData as the app, run silently, would be a one-and-done portable solution); a WMI ping like that takes effectively no processing time to return.
Or is there a larger issue I'm missing?

**Comment by ElPumpo** [comment]
> Or is there a larger issue I'm missing?
No, just a bad design by me. I'll start working on it now . . .

**Comment by seagull** [comment]
I'm no developer, but I'm handy with a batch script. Let me know if you need a hand.

**Comment by ElPumpo** [comment]
I'm good man. I've finished your request, so now we'll assume based on the gpu name.
Example: GTX 970**M** compared to GTX 970

**Comment by seagull** [comment]
That's a much more swish way of doing it, yeah, provided Nvidia give out
reliable information.
If you have some diagnostic code I'm happy to run it here to confirm it
picks up my 960M correctly.

**Comment by ElPumpo** [comment]
ok great, now let's do more shit

**Comment by seagull** [comment]
large
