### ISSUE TITLE
Change client update frequency

### ISSUE THREAD

**Issue by coldner** [ElPumpo/TinyNvidiaUpdateChecker#200]
Currently, when the "Ignore" button is used, it skips the update for only one Windows session. After a reboot, TinyNvidiaUpdateChecker asks again about the same update. The "Skip update" option would be very useful for users who update drivers only from time to time.

**Comment by ElPumpo** [comment]
Hi and thanks for the feedback. Yes it's a good suggestion. I will probably implement this in the next update.

**Comment by ElPumpo** [comment]
Since TNUC is heavily reliant on the NVIDIA API which historically has been volatile I do recommend that updates are regularly checked for it. To properly modify the frequency TNUC should notify users to check for update if they run into an error, and update has not been checked for x time.

**Comment by ElPumpo** [comment]
Have considered this a bit and no, it's not going to happen. But a self updater has been developed.
