### ISSUE TITLE
WinRAR 7 update causes Win32Exception on "Extracting drivers" phase

### ISSUE THREAD

**Issue by dyni00** [ElPumpo/TinyNvidiaUpdateChecker#201]
hello!

works superb but,  look at: i have installed winrar 7b1

![TinyNvidiaUpdateChecker_2_cdlLZZEzID](https://github.com/ElPumpo/TinyNvidiaUpdateChecker/assets/46699227/37829a26-62ea-4ccd-a7c5-f633af386880)

**Comment by ElPumpo** [comment]
Hi and thanks for reporting this issue! It looks like they changed the registry entry for installation path... will investigate.

**Comment by ElPumpo** [comment]
v1.17.1 will shortly be released with issue adressed fix
