### ISSUE TITLE
Slow internet connect on login causes TNUC exception

### ISSUE THREAD

**Issue by Sgt-Nukem** [ElPumpo/TinyNvidiaUpdateChecker#203]
Since some time now TNUC crashes 2 in 3 times with the following message:

![image](https://github.com/ElPumpo/TinyNvidiaUpdateChecker/assets/4144388/1a9ce508-f157-4923-8dab-0c3ae9886081)

(This also happened in some older versions.)

I have a shortcut in shell:startup so it runs once on every login.
But as I usually let the PC hibernate there can be 1-2 weeks until the next restart (when the error pops up). I get it for some months now - every now and then.

I am running it manually some more times then - until it exits successfully.

I suggest sleeping 2 seconds and retrying when the connection could not be made. Try this 3 times in a loop.

**Comment by ElPumpo** [comment]
Hi. Yes it seems like your internet connection takes a while to connect. Are you using a wifi connection?

**Comment by Sgt-Nukem** [comment]
> Hi. Yes it seems like your internet connection takes a while to connect. Are you using a wifi connection?

No, I am not.

**Comment by ElPumpo** [comment]
Oh okay so this happens even if you run TNUC manually?

**Comment by ElPumpo** [comment]
I recommend you delay the start of TNUC. I already have a network connection test..
