### ISSUE TITLE
[Request] NanaZip Support

### ISSUE THREAD

**Issue by nigiriemoji** [ElPumpo/TinyNvidiaUpdateChecker#205]
Greetings, could you please add support for NanaZip? I mostly use it over 7zip because it has Windows 11 Context Menu and is actively on the MS Store

https://github.com/M2Team/NanaZip

Stable: https://www.microsoft.com/store/productId/9N8G7TSCL18R
Preview: https://www.microsoft.com/store/productId/9NZL0LRP1BNL

Thanks

**Comment by ElPumpo** [comment]
Hi. Thanks for the suggestion. The delay is because my Windows installation has somehow been corrupted, I can no longer update or/and install apps in Store.. I'm trying to figure what the hell happened..

**Comment by ElPumpo** [comment]
I know it's delayed.. for some reason my Mircosoft Store has corrupted. I can no longer install any new apps, I've tried everything.. perhaps I can manually download the app...

**Comment by nigiriemoji** [comment]
Thanks very much for the update

**Comment by ElPumpo** [comment]
Yea I cannot install new apps or update existing ones. My app "database" has gone corrupted..

**Comment by ElPumpo** [comment]
Yea sorry not sorry, not going to reformat my PC just to implement this. But I could just use a VM..

**Comment by ElPumpo** [comment]
Okay quick research shows that NanaZip does not have CLI support. So this is impossible. Closing request.

**Comment by ElPumpo** [comment]
Apparently it has undocumented CLI tools: `NanaZipC` and `NanaZipG`

**Comment by ElPumpo** [comment]
![image](https://github.com/ElPumpo/TinyNvidiaUpdateChecker/assets/12564301/0e895b30-9caf-404c-8e08-47794f70155c)
Progress
