### ISSUE TITLE
Custom paths for extract libary

### ISSUE THREAD

**Issue by ronen1n** [ElPumpo/TinyNvidiaUpdateChecker#207]
Most of my apps are portable, so passing the location of the app in parameter or configuring it in config file will be perfect

7zip portable support by `--7zip-location` or something like it

**Comment by ElPumpo** [comment]
Hi @ronen1n. TNUC supports custom locations for the extract libraries. But you can currently not customize it to your liking. I don't really like the idea of a command arg but perhaps an optional config thing.

**Comment by ElPumpo** [comment]
Ok will be added in next release, I've added optional config entries for this. See wiki https://github.com/ElPumpo/TinyNvidiaUpdateChecker/wiki/Configuration-File

**Comment by ronen1n** [comment]
Any way I can save the config file/s in the same folder as the executable instead of appdata folder?

**Comment by ElPumpo** [comment]
Yes if you run it with `--config-here`

**Comment by ronen1n** [comment]
> Yes if you run it with `--config-here`, there's also `--config-override=""`

Perfect, thanks
