### ISSUE TITLE
Network Interface Binding.

### ISSUE THREAD

**Issue by sonikku** [ElPumpo/TinyNvidiaUpdateChecker#209]
I use surfshark with split tunneling on. When I try to run Tiny I get the error; "The requested address is not valid in this context." Works fine without any VPN on though. If possible could you make a flag to bind to IP and/or interface device?

**Comment by ElPumpo** [comment]
Hi. I have no expertice in this matter I will have to do more research..

**Comment by ElPumpo** [comment]
Not enough people need this feature so the request has been denied
