### ISSUE TITLE
Run quietly installed the entire driver in Windows 10

### ISSUE THREAD

**Issue by Neobond** [ElPumpo/TinyNvidiaUpdateChecker#211]
Windows 10 up to date, ran 1.17.1 with  --quiet --confirm-dl as administrator.

I was kind of shocked to see GeForce Experience on the desktop after it completed, and yep.. FrameView, GeForce Experience, HD Audio Driver, PhysX apps were installed.

I thought quiet only updated existing apps, but this seems to install missing ones too.

**Comment by ElPumpo** [comment]
Hi Neo. This is normal behaviour and what you are describing is what TNUC does. There's no claim that TNUC only update what you have already have within the NVIDIA package.

The only alternative for you at the moment is to use the Minimal install feature which only installs the core GPU driver. But currently it is limited as you cannot choose what components you want.
