### ISSUE TITLE
1.18.0 opens then closes

### ISSUE THREAD

**Issue by f33d13ack** [ElPumpo/TinyNvidiaUpdateChecker#216]
It just closes when I try to open it, I see the command window open for a blink of an eye.

Is this intended? Am I missing something?

I was running 1.17.1 before, no issues.

**Comment by scotttag** [comment]
What does it say if you run it from the command line (instead of just opening the exe)? It should give you more details

Chances are you don't have .NET 8.0 runtime (new version requires 8.0) - it'll tell you that if so, along with which frameworks you do have

**Comment by ElPumpo** [comment]
Hi @f33d13ack . Can you please run TNUC with the `--debug` command line argument?

**Comment by ElPumpo** [comment]
Hi a new version, v1.18.1 has been released with many bug fixes. Please try the new version out and report back.

**Comment by f33d13ack** [comment]
Thanks everyone, turns out I just needed runtime 8.0.6 (x86).  I had 8.0.0 (x64) before as well.

Thanks again!

**Comment by ElPumpo** [comment]
Wait. Does Windows not show a dialog to install it?

**Comment by f33d13ack** [comment]
For reference, I'm on whatever the latest version of Windows 10 Pro (x64) is.

When I run it through cmd, at the bottom of the prompt message I get:

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=8.0.0&arch=x86&rid=win10-x86

Otherwise, for me, if the desktop version of the 8.0.6 (x86) runtime, is not installed, I do not get a Windows dialog to install it when clicking on the executable, I just get a window that flashes on then off, that goes for both 1.18.0 & 1.18.1.

**Comment by ElPumpo** [comment]
OK I've added back the .NET 8 installation steps in readme

**Comment by hubertsng** [comment]
> For reference, I'm on whatever the latest version of Windows 10 Pro (x64) is.
> 
> When I run it through cmd, at the bottom of the prompt message I get:
> 
> To install missing framework, download: https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=8.0.0&arch=x86&rid=win10-x86
> 
> Otherwise, for me, if the desktop version of the 8.0.6 (x86) runtime, is not installed, I do not get a Windows dialog to install it when clicking on the executable, I just get a window that flashes on then off, that goes for both 1.18.0 & 1.18.1.

I know this is closed but I believe you put the wrong download. I think you want .NET Desktop Runtime, not .NET framework, [direct download to 8.0.6](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-8.0.6-windows-x86-installer), [main page of .NET 8.0](https://dotnet.microsoft.com/en-us/download/dotnet/8.0)
