### ISSUE TITLE
 1.18.0 No NVIDIA driver was found for your system configuration (gpuID: 0)

### ISSUE THREAD

**Issue by hubertsng** [ElPumpo/TinyNvidiaUpdateChecker#218]
When I open the 1.18 download after upgrading from the 1.17.1, I get the following error:

```
Retrieving GPU information . . . ERROR!
No NVIDIA driver was found for your system configuration.

Debugging information:
gpuID: 0
osID: 135
isDchDriver: 1
driverType: grd
```

Restarting did not fix the issue. Switching back to 1.17.1 does fix the issue as it's able to successfully identify my GPU. I'm using an ASUS x670e-i ITX Motherboard with an NVIDIA GeForce 3070 Founder's Edition. I'm on the latest GRD driver. 555.99 from June 04, 2024 (that I downloaded and installed with -minimal with TinyNvidiaUpdateChecker). 

I don't know if this is an NVIDIA issue as the previous threads with a similar error have people posting a valid gpuID (non-zero).

**Comment by ElPumpo** [comment]
Hi. Yes a bit strange. Well you had id 0 but the code should not go this far in that case. I will investigate

**Comment by SB97** [comment]
I have the same Problem.

```
Debugging information:
gpuID: 0
osID: 57
isDchDriver: 1
driverType: grd
```

**Comment by ElPumpo** [comment]
Guys do you have one GPU only, can you show your GPU in Device Manager?

**Comment by SB97** [comment]
> Guys do you have one GPU only, can you show your GPU in Device Manager?

![grafik](https://github.com/ElPumpo/TinyNvidiaUpdateChecker/assets/20126520/3a7354a2-6dfc-4765-a923-534c2a63b67d)

I have one 'real' GPU and an integrated Graphic Unit in my CPU (AMD Ryzen 7 7700)

**Comment by ElPumpo** [comment]
[TinyNvidiaUpdateChecker v1.18.1 DEV1.zip](https://github.com/user-attachments/files/15720064/TinyNvidiaUpdateChecker.v1.18.1.DEV1.zip) please try this beta build

**Comment by Emilien-Etadam** [comment]
> [TinyNvidiaUpdateChecker v1.18.1 DEV1.zip](https://github.com/user-attachments/files/15720064/TinyNvidiaUpdateChecker.v1.18.1.DEV1.zip) please try this beta build

It resolve the problem for me .
![mmc_BFVUGQrw3M](https://github.com/ElPumpo/TinyNvidiaUpdateChecker/assets/56485277/db3bc520-9821-4044-9728-3d33a9ec76a4)

**Comment by ElPumpo** [comment]
Okay I found it lol, new release coming. DEV1 build did not properly resolve the issue

**Comment by ElPumpo** [comment]
Okay v1.18.1 has been released with fixes to many bugs that would cause gpuID 0 or crash, they all relate to having more than 1 GPU but only one compatible

**Comment by SB97** [comment]
Looks like v1.18.1 works for me now. Thanks for the fast fix!

**Comment by hubertsng** [comment]
Yep, just tried 1.18.1 and it worked for me too. Thanks for the fast fix!

**Comment by Emilien-Etadam** [comment]
Problem is back with v 1.18.2 : 
![WindowsTerminal_jiDDeJEPkQ](https://github.com/ElPumpo/TinyNvidiaUpdateChecker/assets/56485277/8c4cc6aa-0a33-4e27-8080-1726364b9bf3)
