### ISSUE TITLE
GPUs with 'different' PNP ID crashes with IndexOutOfRangeException

### ISSUE THREAD

**Issue by harjeevan** [ElPumpo/TinyNvidiaUpdateChecker#219]
Running the program after installing .NET 8.0.6 x86 is throwing an error.

`Retrieving GPU information . . . Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at TinyNvidiaUpdateChecker.MainConsole.GetDriverMetadata() in C:\Users\Samuel\Documents\GitHub\TinyNvidiaUpdateChecker\TinyNvidiaUpdateChecker\MainConsole.cs:line 422
   at TinyNvidiaUpdateChecker.MainConsole.Main(String[] args) in C:\Users\Samuel\Documents\GitHub\TinyNvidiaUpdateChecker\TinyNvidiaUpdateChecker\MainConsole.cs:line 151`

I'm on Win 11 Pro 23H2 22631.3672. I'm trying to run the newest version (1.18.1)

**Comment by ElPumpo** [comment]
Hi I will investigate this issue. Can you show a screenshot of your GPU in device Manager?

**Comment by cyrilschreiber3** [comment]
Here is the driver properties page for my GPU
![image](https://github.com/ElPumpo/TinyNvidiaUpdateChecker/assets/71042995/d635d4df-a52c-4bec-98a5-fe71e853eb33)

**Comment by ElPumpo** [comment]
Good. Is that your only GPU?

**Comment by ElPumpo** [comment]
![image](https://github.com/ElPumpo/TinyNvidiaUpdateChecker/assets/12564301/6896b93f-7fc0-4615-8776-232cfc12000b)
No guys I need you to show your GPUs in this list

**Comment by ElPumpo** [comment]
Or wait do this instead:
` Get-CIMInstance -Query "SELECT Name, Caption, PNPDeviceID from Win32_VideoController"` run this in PowerShell and post the output

**Comment by ElPumpo** [comment]
Thanks, yes I found the issue. The virtual driver "Virtual Desktop Monitor" PNP Device ID is `ROOT\DISPLAY\0000`. I'll work on a fix for this

**Comment by ElPumpo** [comment]
[TinyNvidiaUpdateChecker v1.18.2 dev.zip](https://github.com/user-attachments/files/15743498/TinyNvidiaUpdateChecker.v1.18.2.dev.zip)

please try this dev build

**Comment by harjeevan** [comment]
same error, different line
`System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at TinyNvidiaUpdateChecker.MainConsole.GetDriverMetadata() in C:\Users\Samuel\Documents\GitHub\TinyNvidiaUpdateChecker\TinyNvidiaUpdateChecker\MainConsole.cs:line 388
   at TinyNvidiaUpdateChecker.MainConsole.Main(String[] args) in C:\Users\Samuel\Documents\GitHub\TinyNvidiaUpdateChecker\TinyNvidiaUpdateChecker\MainConsole.cs:line 157`

**Comment by ElPumpo** [comment]
[TinyNvidiaUpdateChecker v1.18.2 dev 2.zip](https://github.com/user-attachments/files/15743723/TinyNvidiaUpdateChecker.v1.18.2.dev.2.zip)

ok please try this one

**Comment by harjeevan** [comment]
works for me

**Comment by ElPumpo** [comment]
What? I didn't change anything I just added more debug stuff

**Comment by harjeevan** [comment]
Yeah, I've downloaded both and run them in powershell (non-admin)

`PS C:\Users\Harjeevan\Downloads> & '.\TinyNvidiaUpdateChecker v1.18.2 dev.exe'
TinyNvidiaUpdateChecker v1.18.1

Verifying internet connection . . . OK!

Searching for Update . . . OK!

Retrieving GPU information . . . Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at TinyNvidiaUpdateChecker.MainConsole.GetDriverMetadata() in C:\Users\Samuel\Documents\GitHub\TinyNvidiaUpdateChecker\TinyNvidiaUpdateChecker\MainConsole.cs:line 388
   at TinyNvidiaUpdateChecker.MainConsole.Main(String[] args) in C:\Users\Samuel\Documents\GitHub\TinyNvidiaUpdateChecker\TinyNvidiaUpdateChecker\MainConsole.cs:line 157
PS C:\Users\Harjeevan\Downloads> & '.\TinyNvidiaUpdateChecker v1.18.2 dev 2.exe'
TinyNvidiaUpdateChecker v1.18.1

Verifying internet connection . . . OK!

Searching for Update . . . OK!

Retrieving GPU information . . . OK!
There is no new GPU driver available, you are up to date.

Press any key to exit...`

**Comment by harjeevan** [comment]
works too;

TinyNvidiaUpdateChecker v1.18.1

Verifying internet connection . . . OK!

Searching for Update . . . OK!

Retrieving GPU information . . . Ignoring weird device: ROOT\DISPLAY\0000
OK!
There is no new GPU driver available, you are up to date.

Press any key to exit...

**Comment by ElPumpo** [comment]
Exactly. So dev 2 was essentially dev 1 but I accidently sent you the wrong exe woops.

**Comment by ElPumpo** [comment]
Thanks for your help v1.18.2 will be released shortly
