### ISSUE TITLE
7-Zip installed using Ninite not supported

### ISSUE THREAD

**Issue by unsynaps** [ElPumpo/TinyNvidiaUpdateChecker#22]
This may be because I am using the 64 bit version?

**Comment by ElPumpo** [comment]
Damnit, I'll look into this in a few hours...

**Comment by ElPumpo** [comment]
[TinyNvidiaUpdateChecker v1.9.1-beta.zip](https://github.com/ElPumpo/TinyNvidiaUpdateChecker/files/1339772/TinyNvidiaUpdateChecker.v1.9.1-beta.zip)
try this build

**Comment by dabzz** [comment]
I'm getting a "file already open by another user" error in the 7zip extraction dialog.

**Comment by ElPumpo** [comment]
@dabzz what version of 7-Zip are you using?

**Comment by dabzz** [comment]
@ElPumpo latest stable 16.04 64bit installed with Ninite. 7z.exe, 7zG.exe and 7zFM.exe are all located under C:\Program Files\7-Zip.

**Comment by ElPumpo** [comment]
Have you tried erasing the directory where the driver file is located at? If you're using `Download + Install` then look in `%temp%` for e.g `385.69` and erase the directory

**Comment by dabzz** [comment]
Yes, deleted temp and tried only Download + Extract into a folder I created on C:\.
I will play around a little bit more when I get back home.

**Comment by ElPumpo** [comment]
In the root of `C:\`?! Are you sure that you have the sufficient permissions? and yea the application should have a check if the selected directory is writable.

**Comment by dabzz** [comment]
C:\scripts... I can right click > 7zip > "extract here" without UAC popup.

**Comment by ElPumpo** [comment]
`file already open by another user` is 99.9% the result of an IO error, it is probably be that 7-Zip isn't launched with the sufficient permissions - this is not an error on my side, TNUC only points to where the archive is located.
Try running TNUC as admin, that might help... and why are you putting stuff in the root of your hard drive? It is a bad practice.

**Comment by pulse-wave** [comment]
I've same issue, the installer doesn't detect 7zip and ask me to deselect minimal mode, but 7zip is in fact installed, I also tried your 1.9.1 beta but still no luck.

I have the latest version of 7zip, the only different thing is that is not installed in the default directory, because I installed it with scoop, so if it's a matter of installation directory, is there any hack I can do to force tinyNvidiaInstaller look for 7zip in a non default directory?

**Comment by ElPumpo** [comment]
@pulse-wave so I've learned that scoop installs everything in the current user only, and does not touch registry? trying out now...

**Comment by MrJustMe** [comment]
My 7zip is in a different folder not in the defult one so:
Can you add an option like...?
```
If 7zip folder/exe/dll is not found then
	Ask If 7zip is already installed then 
		If yes then
			ask for 7z.exe location
			*save path and name of the exe
			ask for 7z.dll
			*save path and name of the dll
		Else
		End
	    Else
		msg: 7zip is not installed
	    End
End
```
Perhaps you need to write the output in a config.txt file and look for it and read it every time you start the tiny program.
If you do not want to implement it or add a config file or whatever, simply do as if this comment was never posted.

**Comment by ElPumpo** [comment]
@MrJustMe have you tried the application? As long as you're using the installer it will be found automatically.

**Comment by MrJustMe** [comment]
> @MrJustMe have you tried the application? As long as you're using the installer it will be found automatically no matter where it is installed.
I do not use 7zip so i do not use the installer, i use peazip, the application does not find 7zip because it is in a different folder:
In 64 bits version:
`C:\Program Files\PeaZip\res\7z\`
In 32 bits version of peazip the directory should be diferent, and some people install their apps even in different hard disks.

**Comment by ElPumpo** [comment]
Currently PeaZip does not include `7zG.exe`, which is what TNUC uses. If you manually download 7zip and extract it to (in this case) `C:\Program Files\PeaZip\res\7z\` then that would work

I can implement a check for if PeaZip is installed, but would require it to be installed using a installer - and then check if `\7z\7zG.exe` exists

I can also do an automatic install of 7-zip in the directory....

**Comment by MrJustMe** [comment]
nvm and thanks anyway.

**Comment by ElPumpo** [comment]
https://github.com/ElPumpo/TinyNvidiaUpdateChecker/blob/master/TinyNvidiaUpdateChecker/LibaryHandler.cs#L50 Support for 7-Zip has been extended. It checks for many things, see the above.

**Comment by ElPumpo** [comment]
v1.10.0 released! try the build and report back please!

**Comment by ElPumpo** [comment]
I've tested it myself, and works great - closing!
