### ISSUE TITLE
1.19.0 fails with error: Unable to interact with NVIDIA API.

### ISSUE THREAD

**Issue by Antelope13** [ElPumpo/TinyNvidiaUpdateChecker#225]
Previous versions worked. 

```
PS C:\Users\example> TinyNvidiaUpdateChecker
TinyNvidiaUpdateChecker v1.19.0

Verifying internet connection . . . OK!

Searching for Update . . . OK!

Retrieving GPU information . . . ERROR!
Unable to interact with NVIDIA API.

Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at TinyNvidiaUpdateChecker.MainConsole.GetDriverDownloadInfo(Int32 gpuId, Int32 osId, Boolean isDchDriver) in C:\Users\Samuel\Documents\GitHub\TinyNvidiaUpdateChecker\TinyNvidiaUpdateChecker\MainConsole.cs:line 553

Press any key to exit...
```

PC:  Dell Precision 7770
GPU: Nvidia RTX A3000 12 GB Laptop GPU
Driver version: 555.99
Driver Type: DCH

**Comment by ElPumpo** [comment]
@Antelope13 this is a weird issue because the API should never return empty / non-json code. Do you have studio drivers oped in for? Because your GPU does not have them and it would cause a non found result, but not this.

https://gfwsl.geforce.com/services_toolkit/services/com/nvidia/services/AjaxDriverService.php?func=DriverManualLookup&pfid=956&osID=135&dch=1&upCRD=0

Open this link and show the result

**Comment by Antelope13** [comment]
@ElPumpo Looks like the problem is probably on my end due to something in my company's network, probably security related? v1.19.0 fails when I'm on my company WiFi, even though your link returns valid json in browser and older versions of TNUC work. v1.19.0 works when I switch to a non-company network. Not sure why IT doesn't like the new version...

Thanks for looking into it. I should have checked the network first.
