### ISSUE TITLE
Build is x86?

### ISSUE THREAD

**Issue by Nonymus** [ElPumpo/TinyNvidiaUpdateChecker#226]
Hi there,

tried the new build 1.19.0, Windows comlained it is missing the appropriate dotnet version. Noticed it says `Architecture: x86`, which seems odd:

```
E:\Tools\Tiny Nvidia Update>TinyNvidiaUpdateChecker.exe
You must install or update .NET to run this application.

App: E:\Tools\Tiny Nvidia Update\TinyNvidiaUpdateChecker.exe
Architecture: x86
Framework: 'Microsoft.NETCore.App', version '8.0.0' (x86)
.NET location: C:\Program Files (x86)\dotnet\

The following frameworks were found:
  3.1.32 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  5.0.17 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  7.0.20 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=8.0.0&arch=x86&rid=win10-x86

E:\Tools\Tiny Nvidia Update>TinyNvidiaUpdateChecker.exe
You must install or update .NET to run this application.

App: E:\Tools\Tiny Nvidia Update\TinyNvidiaUpdateChecker.exe
Architecture: x86
Framework: 'Microsoft.NETCore.App', version '8.0.0' (x86)
.NET location: C:\Program Files (x86)\dotnet\

The following frameworks were found:
  3.1.32 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  5.0.17 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  7.0.20 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=8.0.0&arch=x86&rid=win10-x86
```

Installing the x86 framework, the app starts, but fails to find GPU information:
```
E:\Tools\Tiny Nvidia Update>TinyNvidiaUpdateChecker.exe
TinyNvidiaUpdateChecker v1.19.0

Verifying internet connection . . . OK!

Searching for Update . . . OK!

Retrieving GPU information . . . ERROR!
No NVIDIA driver was found for your system configuration.

Debugging information:
gpuId:       995
osId:        57
isDchDriver: True
driverType:  grd

Press any key to exit...
```

1.18.2 works without issue.

**Comment by Technetium1** [comment]
That is the expected dependency: https://github.com/ElPumpo/TinyNvidiaUpdateChecker#dependencies

**Comment by ElPumpo** [comment]
@Nonymus yes you didn't read the readme. Wait that sounds funny. Why didn't you read the file that says to read me?

**Comment by Nonymus** [comment]
@ElPumpo Indeed, I don't tend to re-read a README on a minor patch. As you can see from the inital post, however, I was still smart enough to follow the error message on screen and already installed x86 runtime. But even with that, I get the `No NVIDIA driver was found for your system configuration.`, which I didn't get in previous version. As I said, downgraded to 1.18 again, and it works fine.  Maybe you didn't read the full issue description? But why wouldn't you? ;)

Joking aside though, I don't see which information in the README helps me finding the cause for the real error. The framework part I get, but not the second error.

**Comment by ElPumpo** [comment]
No actually you are correct. I've said to many other and I'll said again. I was under the impression that .NET 8 added a prompt to install instead of just closing without any information without running using a terminal.

This was not the case.. so what do I do now, I'm not sure.
