### ISSUE TITLE
No NVIDIA driver found, RTX 3080TI, AtlasOS

### ISSUE THREAD

**Issue by BigFatDeuce** [ElPumpo/TinyNvidiaUpdateChecker#229]
Hello there, the soft used to work but randomly stopped working and now shows this error: https://imgur.com/a/QCpqP2a

I use AtlasOS, and yes, I have the newest NVIDIA driver for my RTX 3080TI installed and clean reinstalled, yet the problem persist.

**Comment by ElPumpo** [comment]
Hi. I see in your screenshot that OS Id was 19.. which is strange. I have never heard about AtlasOS, will have to investigate

**Comment by BigFatDeuce** [comment]
Thanks for your answer, this is basically a 'mod' used on windows to optimize it, mostly for games. And it works surprisingly well, using it for half a year and never really encountered issues.

Additional info, I use the Windows 11 version.

**Comment by ElPumpo** [comment]
Not gonna lie it sounds super gimmicky and sketchy at the same time. I will have to install this thing on a VM to reproduce the issue.. will see

**Comment by ElPumpo** [comment]
OK I have done some research and this is what I am concluding:

1) AtlasOS is super gimmicky, no statistical significant data on performance and an easy way to get all malware. It's all fucking qualitative and nothing quantitative. Are its developers known, and trustworthy? Why would you ever disable security for tiny performance? You're asking to get hacked and it's scrubbing the bottom activity.

2) There's nothing wrong with TNUC. I don't know why they made AtlasOS made it report as Windows 7, that's on their end. You'll have to ask them about this.

**Comment by BigFatDeuce** [comment]
I guess you did a google search and got those infos from there, yes, it disable a lot of things but it gives you the liberty to not disable it when you do your first setup, as a non-retarded person, I of course kept windows defender along other things, my goal with that was to try out a windows version that is debloated out of the box and, as they claim, optimized for gaming, and surprisingly I saw a noticeable increase of FPS in certain games.

It's not for people that don't know what their doing of course.

So apparently the issue is that AtlasOS shows itself as a windows 7 version. That is quite weird, as I said, I used your soft for some months with no issue whatsoever. Tho I understand that you don't want to spend time to fix a thing for such a low amount of users. Still, thanks for that software. I make everyone I know & customers use it instead of having to deal with Geforce Experience, no account needed, no data gathering from NVIDIA too.

**Comment by ElPumpo** [comment]
I have a strong bias against modifications to the system from unknown developers. Microsoft are known, they wouldn't infect your software. Who are these developers? They have no reputation.

It's not about what "google search" results say, cmon. It's my brain flashing red warning signals. If you actually think with your own brain for a moment without what the "internet" says you'd realize the same.

To clarify, AtlasOS reports as Windows 7. [Here's the exact code](https://github.com/ElPumpo/TinyNvidiaUpdateChecker/blob/093815a6139705d8b6259e1603de12e8ff95f706/TinyNvidiaUpdateChecker/MainConsole.cs#L415)

**Comment by BigFatDeuce** [comment]
Considering that Microsoft plans to take screenshots from your PC for their AI bs, I wouldn't blindly trust them either.
