### ISSUE TITLE
7zip scoop not found

### ISSUE THREAD

**Issue by pulse-wave** [ElPumpo/TinyNvidiaUpdateChecker#23]
@ElPumpo I decided to open up another issue for the 7zip\scoop support, unfortunately still doesn't work, the problem I guess is pretty easy to fix if you already fixed for the users\scoop.

The problem is that scoop let you install in two ways locally (using the local folder of the user the one you fixed I guess), and globally with the flag -g that will install 7zip in C:\ProgramData\scoop\apps\7zip\current (the path is the same of the local one I guess except is in C:\ProgramData\scoop).

Could you please add it aswell? so systems with 7zip installed globally will work as well thank you very much!

**Comment by ElPumpo** [comment]
[TinyNvidiaUpdateChecker v1.9.1-beta 3.zip](https://github.com/ElPumpo/TinyNvidiaUpdateChecker/files/1347421/TinyNvidiaUpdateChecker.v1.9.1-beta.3.zip) this build has support for scoop installs

**Comment by pulse-wave** [comment]
this works great with scoop thanks

**Comment by ElPumpo** [comment]
No problem man! Hope you enjoy the application!
