### ISSUE TITLE
Nagging for .NET 8 tuntime install even though it is already installed

### ISSUE THREAD

**Issue by clin1234** [ElPumpo/TinyNvidiaUpdateChecker#236]
![image](https://github.com/user-attachments/assets/028ea230-7511-4f3d-950c-3d5315fea9a2)

Even though it is already installed:
```pwsh
PS C:\Users\ךינשגכהד> "NETCore","WindowsDesktop"|%{ls "c:\program files\dotnet\shared\Microsoft.$_.App"}


    Directory: C:\program files\dotnet\shared\Microsoft.NETCore.App


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         7/27/2024  12:46 PM                8.0.7


    Directory: C:\program files\dotnet\shared\Microsoft.WindowsDesktop.App


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         7/27/2024  12:47 PM                8.0.7

```

**Comment by clin1234** [comment]
Unfortunately, yes.

**Comment by ElPumpo** [comment]
Thats strange. This isnt NET support but I suggest you run the 'repair' on its runtimes from install / uninstall programs. Try a complete reinstall of all runtimes.

We have also previously had issues with users installning the net sdk from scoop, in this case uninstalling it solved the problem.

**Comment by clin1234** [comment]
Already tried running Repair; didn't work. Perhaps I need to raise the issue with dotnet directly...

**Comment by ElPumpo** [comment]
Yes, I am unable to help you.

**Comment by Gesugao-san** [comment]
Hi! I'm has been hit by same problem.
@clin1234 any updates with dotnet?

**Comment by HawaiiBeach** [comment]
Hey @Gesugao-san

First off, do you have .NET 8 runtime installed?

Do this:

Go here https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-8.0.31-windows-x64-installer

If it's already installed, go to control panel and uninstall it. Then install it again with the link above.
Let me know what happens

**Comment by clin1234** [comment]
Found my solution: `set DOTNET_ROOT=`
