### ISSUE TITLE
Hi metadata not working for ASUS GEFORCE GTX 1060 6G

### ISSUE THREAD

**Issue by tzx39** [ElPumpo/TinyNvidiaUpdateChecker#237]
PLS HELP

**Comment by tzx39** [comment]
sorry it works

**Comment by tzx39** [comment]
Windows didn't find the GPU at first, but after 2 minutes it detected it, and now it's working, 
I'm sorry for writing about the problem too quickly. have a nice day

**Comment by ElPumpo** [comment]
Okay man good to hear it got resolved 👍
