### ISSUE TITLE
No New GPU Driver Available

### ISSUE THREAD

**Issue by AdrianeNS** [ElPumpo/TinyNvidiaUpdateChecker#238]
I just downloaded the Tiny Update Checker and set it up to look for new Studio drivers.  When I ran the tool, it said there are no new drivers available, however, the NVIDIA app says there is an update available.  My Game Ready drivers are up to date, but the Studio drivers are not.  

I'm not sure if I'm doing something incorrectly or if this is a bug but wanted to let you know.

Thanks for making this program though!  If I can get it to work correctly, I'll definitely keep using it!

**Comment by ElPumpo** [comment]
Hi Adriane!

Could you please run TNUC with the `--debug` argument, and share full output so I could see the details

**Comment by AdrianeNS** [comment]
Sure!  How do I do that?  When I launch it, there isn't any option to input a command.  It automatically searches and then when it's done the only option is to close the window.

**Comment by Technetium1** [comment]
@AdrianeNS Right-click your start button, choose whichever of these is there: `Terminal` or `Command Prompt` or `Powershell`, then drag the file into that window, and add a space then `--debug`, and press Enter. Click and drag to highlight everything since that command, then Enter or right-click to copy to your clipboard, so you can paste here.

**Comment by AdrianeNS** [comment]
Hello again!  I'm sorry for the long delay in my reply.  I got sidetracked with something else and had to shelf this issue.  In any case, I didn't know you could drag a file into the terminal to copy a path so thanks for that!  However, when I enter the debug command I'm getting an error:

```PS C:\Users\adria> "C:\Program Files\My Utilities\TinyNvidiaUpdateChecker.exe" --debug
ParserError:
Line |
   1 |  "C:\Program Files\My Utilities\TinyNvidiaUpdateChecker.exe" --debug
     |                                                                ~~~~~
     | Unexpected token 'debug' in expression or statement.```

**Comment by ElPumpo** [comment]
You're doing it wrong... go watch YouTube how to run arguments in terminal..

**Comment by ElPumpo** [comment]
You still there @AdrianeNS ?

**Comment by AdrianeNS** [comment]
Yes, I'm here, sorry!  I am comfortable using the terminal for commands when I need to.  I'm not sure what's wrong here.  I copied the file path to the executable into terminal, entered a space and then "--debug".  This gives me the unexpected token "debug" error.

**Comment by ElPumpo** [comment]
Just watch youtube man, or I will eventually close the thread.
