### ISSUE TITLE
Won't find a GPU if no nvidia driver was installed.

### ISSUE THREAD

**Issue by Daniil1288** [ElPumpo/TinyNvidiaUpdateChecker#24]
Not sure if this is expected behaviour or not, but on a fresh new windows 7 installation the program will display an error saying "no supported GPUs found". After I installed an outdated nvidia driver, the tool worked just fine (downloaded and installed a new version without geforce experience).

**Comment by ElPumpo** [comment]
Damnit I didn't think about this. How about a dialog asking for an one-time ignore?

**Comment by ElPumpo** [comment]
[TinyNvidiaUpdateChecker v1.9.1-beta 4.zip](https://github.com/ElPumpo/TinyNvidiaUpdateChecker/files/1352085/TinyNvidiaUpdateChecker.v1.9.1-beta.4.zip)
commit 68a628f831d3565af273ec50416ea91d0a435d52 added check against vendor ID if the gpu name doesn't contain the word `nvidia`

aand you might not want to test this :D (you'd have to uninstall drivers and make sure none install) - ill do it myself
