### ISSUE TITLE
Driver installer always force run quietly

### ISSUE THREAD

**Issue by tharos96** [ElPumpo/TinyNvidiaUpdateChecker#25]
For the first time the UpdateChecker didn't open the setup but directly installed the new driver including Geforce Experience and a 3D Vision Preview Kit.
Not quite what I expected and wanted to let you know.

**Comment by tharos96** [comment]
In other words it installed every possible option of the setup without letting me choose.

**Comment by ElPumpo** [comment]
Yea... I'll fix that

**Comment by ElPumpo** [comment]
Fixed in the commit
