### ISSUE TITLE
7zip refuses to extract from downloaded installer

### ISSUE THREAD

**Issue by darealshinji** [ElPumpo/TinyNvidiaUpdateChecker#26]
I'm always getting an error from 7zip that translates to "The process cannot access the file because it's already being used by another process":

![screen-2017-10-10_23-20-15](https://user-images.githubusercontent.com/5700937/31411443-f8e74450-ae11-11e7-9437-8ab9340a1ca5.png)

I'm on Windows 10, only Windows Defender running, no other anti virus program running.
Running TNUC as admin doesn't fix this.

**Comment by ElPumpo** [comment]
At least 2 other people have reported this exact issue. 

Have you tried 7zip 17.04? And what version of 7zip are you currently using

**Comment by darealshinji** [comment]
I was using 16.01. I've now installed 17.04 but in the meanwhile I had updated my drivers manually with the downloaded setup file, so now it just shows that my drivers are up to date.

**Comment by ElPumpo** [comment]
Try running the application again with the `--force-dl` command line argument. I suspect this is a bug related to 7-zip and not the application

**Comment by darealshinji** [comment]
Weird, now it can't find 7zip at all, neither if it's 16.04 or 17.01. Location is always `C:\Program Files\7-Zip`.
Can't you just bundle the command line version of `7z.exe` and use that instead?

Or what about this: if I get it right 7zip is used to extract components for a minimal installation, right? Why not add an option to just start the installer non-quietly so that I can decide which features I want? Because if I click `Download + Install` it'll perform a silent full installation since it doesn't find 7zip.

**Comment by ElPumpo** [comment]
Did you install 7-Zip using the default installer? It should detect the registry keys that the installer creates, and I don't want to implement an automatic download of 7-Zip if you don't have it installed because who doesn't have 7zip (or winrar) in the first place?
Are you on a amd64 system?

**Comment by darealshinji** [comment]
I've reinstalled 7zip using the .exe installer instead of .msi package and now it works. I'm on x64.
If 7zip isn't found in the registry, why not look into the default installation directories?
```
%ProgramFiles%\7-Zip\7zG.exe
%ProgramFiles(x86)%\7-Zip\7zG.exe
```

**Comment by ElPumpo** [comment]
Oh the msi package? I'll add support for it.

**Comment by ElPumpo** [comment]
v1.10.0 released! try the build and report!

**Comment by ElPumpo** [comment]
@albpara what error? What version of 7-Zip are you using?

**Comment by albpara** [comment]
Same error described on the issue, of course.

I was using (mostly sure) the .msi version. I just removed it and downloaded the latest .exe installer and it worked, but unfortunately, version 1.10.0 still threw the error

**Comment by darealshinji** [comment]
Having this issue again, but I figured something out:
If I select "Download + Extract" I get the same error after the download finished. But if I select "Download + Extract" a second time and chose the directory with the already downloaded installer the extraction works.

**Comment by ElPumpo** [comment]
@albpara ok... You never answered what version of 7-Zip you're using

@darealshinji what version of 7-Zip are you using?

Thanks a lot for the feedback btw!

**Comment by albpara** [comment]
Sorry @Elpumpo, I didn’t mention the version because as I said, I updated my 7-zip to latest and I did’n t check before erasing.... I assume that I was using a 16.x but certainly, I am just gessing, sorry about that :(

**Comment by ElPumpo** [comment]
@albpara then try 7-Zip 17.xx versions instead, currently 17.01 which can be found [here](http://www.7-zip.org/download.html)

**Comment by darealshinji** [comment]
Deactivating Windows Defender (temporarily) fixes the problem for me.

**Comment by ElPumpo** [comment]
Then this is a bug related to Defender, and not TNUC. But why can't 7-Zip extract a file used by another process.. kinda silly

**Comment by darealshinji** [comment]
Good question. I wonder if saving the .exe as .7z would trick Defender.

**Comment by darealshinji** [comment]
Changing the extension does nothing. However I did some testing and figured out a few things:

1. WinRAR has no such issues.

2. Running TNUC with `--quiet` does work, 7zG shows no errors and extracts files on the first try. Not sure what's so different about this.

3. Changing the part [here](https://github.com/ElPumpo/TinyNvidiaUpdateChecker/blob/5358b2f6166e2d850d7bce6d70fd6240c96cd30b/TinyNvidiaUpdateChecker/MainConsole.cs#L1008) to
``` cs
try {
    SevenZip.Start();
    SevenZip.WaitForExit();
    SevenZip.Start();
    SevenZip.WaitForExit();
} catch (Exception ex) {
```
makes the second attempt succeed, just as expected.

**Comment by ElPumpo** [comment]
This is really strange... what's causing it...... If you're sure that `Thread.Sleep(1000);` will make it work I'll add it to the code.

**Comment by exadeci** [comment]
@ElPumpo I have the same issue even with 1.10 and just extract fails too.

**Comment by ElPumpo** [comment]
@exadeci this bug doesn't seem to be caused by my application, what version of 7-Zip are you using?

**Comment by exadeci** [comment]
@ElPumpo The last stable one 16.04 (2016-10-04) http://www.7-zip.org/download.html

**Comment by ElPumpo** [comment]
@exadeci then try 17.01

**Comment by ElPumpo** [comment]
[TinyNvidiaUpdateChecker v1.11.0-beta.zip](https://github.com/ElPumpo/TinyNvidiaUpdateChecker/files/1443281/TinyNvidiaUpdateChecker.v1.11.0-beta.zip) this build has the workaround @darealshinji mentioned. Everyone please try it and report back.

**Comment by darealshinji** [comment]
v1.11.0 failed on my first attempt but then it succeeded on all later attempts for me.

**Comment by ElPumpo** [comment]
Can you confirm that it's caused by Defender?

**Comment by darealshinji** [comment]
v1.10 fails with Defender on and succeeds with with Defender off. v1.11 succeeds even if Defender is on.

**Comment by ElPumpo** [comment]
Ok, how about running the application with `--quiet`, as it uses `7z.exe` instead of `7zG.exe`

**Comment by darealshinji** [comment]
That's working but it shows a GUI, so is it really using `7z.exe`?

![screen-2017-11-11_18-14-23](https://user-images.githubusercontent.com/5700937/32691735-77a1219a-c70c-11e7-96be-fd4060fc58b2.png)

**Comment by ElPumpo** [comment]
Wouuups! My bad - you should use the following arguments: `--confirm-dl --quiet --force-dl`

**Comment by darealshinji** [comment]
It's downloading the driver into `%TEMP%/388.13`, silently. But it doesn't seem to do anything else.

**Comment by ElPumpo** [comment]
It runs the nvidia installer without any user interaction, you sure it didn't update your drivers?

**Comment by darealshinji** [comment]
I've checked it again and running `TinyNvidiaUpdateChecker.exe --confirm-dl` on v1.10 updates the driver without any issues.

**Comment by indivisible** [comment]
This looks like a race condition: sometimes you try to extract (read) the file that's still open for writing (the download).

I'm not quite familiar with webclient, but maybe the `DownloadFileCompleted` event should be used, as that's fired later. As I understand `DownloadProgressChanged` is fired as soon as data is received from the network, before writing it to the file.

https://github.com/ElPumpo/TinyNvidiaUpdateChecker/blob/e4a74b53b32cd965d74f9821e72c7224e8b1b90d/TinyNvidiaUpdateChecker/MainConsole.cs#L816

**Comment by ElPumpo** [comment]
I honestly don't know what to do @darealshinji, I've been too lazy (sorry) to test with Defender enabled, I use a third party anti-malware program instead so I have always had Defender disabled.

@indivisible I'm sure that the downloader has nothing to do with it, you can try it yourself if you already have the driver file downloaded and select its folder in TNUC. Also if this were the case, then it would occur to WinRAR users aswell (including me?).

I am taking @darealshinji's word that Defender is causing this problem, but I'll test it myself soon enough.

**Comment by indivisible** [comment]
@ElPumpo 7zip complains about the file being used by another process. Not much else can happen to it to lock out reading.

A lot of things can cause one application to sometimes fail and another to succeed: time from beginning of execution to point of opening the file, how it tries to handle locked files, etc.

There's a really small window of time when this error can occour, so it's normal that many people never see it.

I've looked at the reference implementation of webclient, and it really does fire the progress changed event before actually writing the bytes, so the current behaviour is incorrect anyway.

**Comment by darealshinji** [comment]
Maybe you should recommend only WinRar or point out that there might be issues with 7zip until this is fixed.

**Comment by ElPumpo** [comment]
I'll take a closer look on this issue sooner lor later, but it must be said that I have not contributed enough the past weeks than what I used to. Feel free to help me fixing this issue.

**Comment by SyntaxErrol** [comment]
Issue persists with v1.11.0 and 7-zip 18.01.

**Comment by ElPumpo** [comment]
I still don't get why you guys are experiencing this and I don't. If someone could reproduce it, it could be a great help to fix this issue. @darealshinji's mentioned fix apparently doesn't work. Alternative I'll get started on implementing #35

**Comment by indivisible** [comment]
https://gist.github.com/indivisible/eb4cca2f2465dc80ddf9df180b02971c

There you go, small demonstration that should work for you too.

The PR I submitted is trash, I noticed that you have the exact same download code twice and I only patched 1 of them, badly (need to check 2 fields as you mentioned).

**Comment by ElPumpo** [comment]
I don't think that this is related to the downloader tho, how about we try to isolate the extracting process and let you guys test it.
Thinking about it you can isolate the downloading process by downloading the driver, then exit the program (the driver file will be saved). Now run the application and it'll try to extract it. (requires the second option, do not use the automatic install)

**Comment by indivisible** [comment]
> I'm always getting an error from 7zip that translates to "The process cannot access the file because it's already being used by another process":

Error from the gist:
`System.IO.IOException: 'The process cannot access the file 'C:\Users\me\source\repos\ConsoleApp1\ConsoleApp1\bin\Debug\test.zip' because it is being used by another process.'`

It sure looks suspiciously similar.

**Comment by ElPumpo** [comment]
Sorry for being retarded, expect a beta build fixing this bug in 4 minutes. Thanks for your help.

**Comment by ElPumpo** [comment]
Please try the [new build.zip](https://github.com/ElPumpo/TinyNvidiaUpdateChecker/files/1796614/new.build.zip)

**Comment by indivisible** [comment]
Seems to work now. Thanks a lot!

**Comment by ElPumpo** [comment]
Yet again dude thanks a lot for helping me out! The code example you provided me with helped me understand what was really going on. Releasing v1.12.0 as we speak.

**Comment by indivisible** [comment]
You're welcome!
