### ISSUE TITLE
GPL-incompatible icon

### ISSUE THREAD

**Issue by darealshinji** [ElPumpo/TinyNvidiaUpdateChecker#27]
The icon is licensed under the CC BY-NC 3.0. But that license is incompatible to the GPL because of the "non-commercial" aspect (and probably for other reasons too).
According to [this FAQ](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software) only the CC BY-SA 4.0 license is compatible to only the GPLv3.

**Comment by ElPumpo** [comment]
I know.. CC BY-NC in general isn't compatible with GPLv3, I only see this becoming an issue if a forker would sell the application - that wouldn't be my problem

Aaaand I'm not a lawyer and am a bit unsure what could happen, I've wanted a new icon, but it isn't on my priority list

Closing for now, and I'll open it when the time comes to change the icon.
