### ISSUE TITLE
Let user chose what to extract when using the minimal install feature

### ISSUE THREAD

**Issue by ElPumpo** [ElPumpo/TinyNvidiaUpdateChecker#28]
At the moment we only extract the following files / directories
```csharp
string[] filesToExtract = { "Display.Driver", "NVI2", "EULA.txt", "license.txt", "ListDevices.txt", "setup.cfg", "setup.exe" };
```

The optimal solution would be a GUI with all the packages that the driver offers, [the driver file content has already been documented over at the wiki](https://github.com/ElPumpo/TinyNvidiaUpdateChecker/wiki/Driver-file-content)

**Comment by chross** [comment]
I'd love to see this feature, too as I rely on Optimus for my laptop. However I don't need Experience and all that other stuff.

**Comment by cywq** [comment]
Do you got any wish how the interface should look like @ElPumpo ? This enhancement is the next thing on my list

**Comment by ElPumpo** [comment]
I was thinking a gui with checkboxes for all.. addons. Be aware that many 'addons' have dependencies that must be taken care of in.

**Comment by Cubox-** [comment]
There is software that does this already:
https://www.guru3d.com/files-details/nvidia-driver-slimming-utility.html

Instead of creating the code again, maybe ask the author if you could merge his program into the update checker, or launch his software after a download. What I do when an update is available is download it using TinyNvdiaUpdateChecker, then run NVSlimmer with the exe downloaded, checkbox what I want, and click install.

**Comment by ElPumpo** [comment]
Its a matter of creating a gui for people to select the components they want installed. I'd never require another program for that... Also Ive been extremly busy with other projects the past year :/

**Comment by ElPumpo** [comment]
Apparently you can get the dependencies of components from reading `nvi` files

**Comment by ElPumpo** [comment]
I don't think this is going to be implemented. NVIDIA is working on a GeForce experience replacement I'm not going to develop something that will be invalid soon

**Comment by ElPumpo** [comment]
![image](https://github.com/ElPumpo/TinyNvidiaUpdateChecker/assets/12564301/faea5acb-8088-415f-a8c9-ffdaa10cb1ae)

Progress

**Comment by ElPumpo** [comment]
v1.19.0 yey. This is huge for the project!
