### ISSUE TITLE
Option for custom 7-Zip location

### ISSUE THREAD

**Issue by krisu5** [ElPumpo/TinyNvidiaUpdateChecker#30]
I'm okay with having 7-Zip, but my main software is Bandizip atm.

And I rather use portable 7-Zip, so setting for exe location in config file would nice to have instead of installing 7-Zip unnecessary.

**Comment by ElPumpo** [comment]
Sadly Bandizip doesn't support a list of the content inside an archive to extract. TNUC supports portable installs of 7-Zip, just create a symbolic link and call the folder `7-Zip`.
The coming update will also support a portable 7-Zip location, just specify it in `HKEY_LOCAL_MACHINE\SOFTWARE\7-Zip`
