### ISSUE TITLE
Display local and remote drivers version

### ISSUE THREAD

**Issue by exadeci** [ElPumpo/TinyNvidiaUpdateChecker#31]
It's always nice to know this information if we want to install beta drivers or just check our drivers version and it's a trivial change as you use it already for debug.

**Comment by ElPumpo** [comment]
Thanks for using the application! The local and remote driver versions are shown on the GUI when a new update is available.

**Comment by exadeci** [comment]
I meant showing it when it's up to date too, as for example I read about a driver that improved performance in a game but I didn't know if I had it installed or not.

**Comment by ElPumpo** [comment]
Well you are obviously up-to-date if you run TNUC. You can use the `--debug` argument to see the versions.
