### ISSUE TITLE
PhysX install support

### ISSUE THREAD

**Issue by sick13** [ElPumpo/TinyNvidiaUpdateChecker#34]
In addition to drivers installing, to also add PhysX installation also

**Comment by ElPumpo** [comment]
You mean for the minimal install, right?

**Comment by sick13** [comment]
yeah minimal install Drivers+PhysX, these two are the most crucial in my opinion

**Comment by ElPumpo** [comment]
Kinda related to #28

**Comment by sick13** [comment]
Agreed, the point is to be able to choose these two crucial things, Drivers and physX are for my opinion minimal, everything else is junk for tweaking junkies (like me :D )

**Comment by seba2282** [comment]
What's component are installed in minimal setup by this interesting program? Why mist have winrar? Why example 7zip?

**Comment by seba2282** [comment]
And Nvidia HD Audio install too?

**Comment by ElPumpo** [comment]
Duplication of #28
