### ISSUE TITLE
7zip/WinRar dependency might not be needed

### ISSUE THREAD

**Issue by ghost** [ElPumpo/TinyNvidiaUpdateChecker#35]
It's possible to make the driver archive extract its contents silently and without it automatically launching the setup. The command line switches are -y -gm2 -nr (referenced from https://github.com/chrislake/7zsfxmm/wiki/Switches).
Perhaps implementing the minimal install this way would be a bit less efficient since you will be extracting everything and then deleting the bloatware (everything not whitelisted I suppose) but on the other hand you won't need any third party tool to extract the archive.

**Comment by ElPumpo** [comment]
> Perhaps implementing the minimal install this way would be a bit less efficient since you will be extracting everything and then deleting the bloatware (everything not whitelisted I suppose)

We only extract the driver files, that's why only WinRAR and 7-Zip are supported. I'll look into 7zsfxmm sooner or later.

**Comment by ElPumpo** [comment]
I'm not really interested in changing the current code. Yet again if you really want minimal-install then download its requirements.
