### ISSUE TITLE
--ignore-missing-gpu not extracting drivers

### ISSUE THREAD

**Issue by disgusdad** [ElPumpo/TinyNvidiaUpdateChecker#39]
On a system without an Nvidia GPU, trying to run TinyNvidiaUpdateChecker with --ignore-missing-gpu and selecting download + extract.
The driver package is downloaded but does not extract anything, just leaving the full installer in the designated folder.

This behavior is both with 1.11.0 and most recent source code (1.12.0)

**Comment by cywq** [comment]
cant replicate the error on the current version. Mine extracts fine.

**Comment by ElPumpo** [comment]
#metoo
