### ISSUE TITLE
Setup.exe not working on Windows 7,  "The system cannot find the path specified"

### ISSUE THREAD

**Issue by OneSlize** [ElPumpo/TinyNvidiaUpdateChecker#43]
It worked the first time after a clean install of Win 7 Ultimate but can't use the minimal installer anymore.
I think it has something to do with " Updateuser" folder not being properly handled by the program...
![capture](https://user-images.githubusercontent.com/39633481/40562733-82a53104-6062-11e8-8495-40d21d1601f8.PNG)

**Comment by ElPumpo** [comment]
More duplicates? great
