### ISSUE TITLE
Download from nearest download server

### ISSUE THREAD

**Issue by hl2guide** [ElPumpo/TinyNvidiaUpdateChecker#45]
The download of New Drivers stalls at 9%, then 22% then endlessly runs (does not complete).
_Checking my internet speed shows no bandwidth issue at the time._

![screenshot](https://user-images.githubusercontent.com/17044982/40880858-2ce71822-66fc-11e8-9faa-d3545b90ba83.PNG)

**Comment by cywq** [comment]
#44 should fix this. quickedit is responsible for this. when its enable you select something by clicking inside the console and freezing the whole console output with it.

**Comment by ElPumpo** [comment]
Doesn't seem like the user was selecting the window, if it was then it would change the title of the application... Maybe an issue with nvidia server?

**Comment by cywq** [comment]
I only encountered it when you click on the windows and have a cursor somewhere. 

@hl2guide you could try my quickedit branch if thats fixing the bug

**Comment by hl2guide** [comment]
@ElPumpo I've tried TinyNvidiaUpdateChecker v1.13.0 and I still run into the issue.
To be clear this is what is happening for me:
1. Launched TinyNvidiaUpdateChecker 
2. Clicked download and install button
3. I don't click anything and leave the window focused
4. I downloads up to a point (e.g. 7%, 23% etc), no longer progressing
5. The ASCII spinner endlessly spins

When I try the above with a network traffic monitor open is shows that it stops downloading. Maybe the NVidia file server just gives up the ghost?

**Comment by cywq** [comment]
jsut tried it with the v1.13.0 version and the installation startet in the background. download worked without a problem for me

**Comment by ElPumpo** [comment]
Run the application with the `--debug` argument and screenshot the window

**Comment by hl2guide** [comment]
I ran a debug pass and it decided to complete the download this time and the driver install succeeded.

![result debug mode](https://user-images.githubusercontent.com/17044982/41072630-74fa1d1e-6a42-11e8-87db-b63595b3ea03.png)

It seems to me that the UK server is spotty and often just stops responding. Can I set it to use the US server somehow?

**Comment by florian-kaiser** [comment]
Basicly we only need to find out where GFE is pinging to check for updates for the version check. When we have that we can easily build the download link ourself as its always the same.
Thats where i would look

**Comment by ElPumpo** [comment]
A fix is coming soon! You'll be able to choose download location, I'll keep you all posted.

**Comment by ElPumpo** [comment]
Sorry for the extreme long wait.. I wasn't able to get pinging to work as it looks like they have the same delay due to the configuration. Master branch now has a working location download selector.

**Comment by ElPumpo** [comment]
Closing this issue as a new version will be released shortly
