### ISSUE TITLE
PC restarts without warning

### ISSUE THREAD

**Issue by RoxKilly** [ElPumpo/TinyNvidiaUpdateChecker#48]
When using version 1.13 to update (download + install), the PC restarts without warning at the end of the installation.  A prompt before restarting would make sense to give the user time to save her work

**Comment by ElPumpo** [comment]
Damn does that really happen? Either way it's a very easy fix since I recall there being a command line argument you could pass to the nvidia installer to ignore reboots.

**Comment by cywq** [comment]
Just tried it with the /s command line and it installed successfully without any reboot what so ever

**Comment by ElPumpo** [comment]
Bug should be fixed. We now parse arguments to ignore reboots, keeping this issue open until a new version is released.

**Comment by ElPumpo** [comment]
Closing, a new version will be released shortly!
