### ISSUE TITLE
Geforce 630M - wrong update

### ISSUE THREAD

**Issue by tinect** [ElPumpo/TinyNvidiaUpdateChecker#50]
There is an update listed, not available for the used grafics:
[image](https://user-images.githubusercontent.com/135993/42134705-551e9d96-7d41-11e8-8af3-0365c5f4e006.png)

Related to Nvidia version 391.35 is current for this card, but updater loads everytime above update, without able to install it. Still stays the same.

**Comment by tinect** [comment]
@ElPumpo damn, thanks. should have looked into mobile, instead of desktop.

thank you

**Comment by ElPumpo** [comment]
no probs

**Comment by itsho** [comment]
I'd suggest adding a warning when running the app with unsupported hardware. 
thank you.

**Comment by ElPumpo** [comment]
@itsho do you mind opening an issue for it?

**Comment by itsho** [comment]
sure thing. thank you!
