### ISSUE TITLE
Add support to downlosd Hot-fix , Beta drivers and to process already downloaded drivers 

### ISSUE THREAD

**Issue by Tsoccerguy3** [ElPumpo/TinyNvidiaUpdateChecker#51]
This program does nothing unless you have a internet connection . What if you have to download the driver from another computer , then move it to another machine .
Or during a clean install with no internet connection .

I'm finding that upon the release of new drivers hot fix drivers are released soon after and the Updater checker does not pick up on this . The App needs to check the international site for hot fix or even beta drivers

Add support for when you have the driver already , the program will skip the download and process a local Driver on your drive .

Add a feature , a new GUI with check boxes , to choose what to install , as well as the command line tool

Thanks

**Comment by cywq** [comment]
I looked into the Hotfix as i also wanted to implement it but didnt find any infos about how i can search for these hotfixes. Is there a annoucement website?

As to the local install without internet i will look into it.

**Comment by Tsoccerguy3** [comment]
They get Posted here https://forums.geforce.com/default/board/33/
A good place to ask for international ftp

**Comment by cywq** [comment]
#52 should add the the installing with a downloaded driver and no internet connection.

i dont think they will give us a international frp, will look into it to search the site with HAP and extracting the download link with it.

**Comment by Tsoccerguy3** [comment]
Try this as a starting page https://developer.nvidia.com/nvidia-driver-symbol-server

Apparently you can resolve location of all drivers going back 3 years

**Comment by cywq** [comment]
I think you misread the infos on that site. They serve you the symbols for all drivers going 3 years back and not the binaries of the drivers as that wouldnt be a "symbol server"

**Comment by Tsoccerguy3** [comment]
Solution: Point your debugger at our driver symbol server, https://driver-symbols.nvidia.com/. This is typically done in Visual Studio using the symbol settings menu.

Our driver symbol server can serve you NVIDIA driver binaries from any driver release within the previous 3 years (at the time of writing this article), and includes all the binaries we distribute in our release driver package -- so whether you're developing for DirectX 11, DirectX 12, OpenGL, Vulkan or CUDA and more, you should be covered!

Please note, we are only hosting the driver binaries, no PDBs will be distributed on this server.

**Comment by Tsoccerguy3** [comment]
The answer to get at their server must be somewhere in the Game development platform sdk

**Comment by cywq** [comment]
Thats not really helping as i dont get how i access the binaries on the server. All guides only state that they provide pdb symbol debug files and not binaries.


The SDK can only be downloaded with a developement account

**Comment by ElPumpo** [comment]
There is an API the geforce experience app uses to get all downloads, but I'm not interested in support beta drivers as I've only had issues with them. If you want on-edge drivers than (at least for now) this application is not for you, sorry.

But in the future I'm willing to just use an API to get the current latest driver(s) instead of extracting using HAP since it's an ugly solution tbh.
