### ISSUE TITLE
Cannot Disable Geforce Experience Installation

### ISSUE THREAD

**Issue by KZcheese** [ElPumpo/TinyNvidiaUpdateChecker#53]
In step 2 of the driver installer: _License Agreement_, the installer gives the user the option to install either the Graphics Driver **WITH** Geforce Experience, or **WITHOUT**. 

TinyNvidiaUpdateChecker skips step 2 and selects **WITH** Geforce Experience by default when _Download + Install_ is selected. This means the only way I can update drivers without installing Geforce Experience is to extract them first then manually run the installer.

This was tested on 2 computers, one with a desktop GTX 1080 and one with a GTX 970m in optimus. Both systems are running up to date Windows 10.
![image](https://user-images.githubusercontent.com/8646140/44879642-4a747800-ac78-11e8-80b1-c7561f012a0e.png)

**Comment by ElPumpo** [comment]
Damnit, it's because we're using a command line argument that bypasses the license agreement. I'll look into it.

**Comment by Yrlish** [comment]
I would love to have this bug fixed. Really annoying.

**Comment by Precigus** [comment]
I second that, the bug is truly annoying, just ran into it myself. Just not sure, if it actually bypasses the step, or is it that it downloads a different version of the installer, since there is one which doesn't even give you the option to choose whether you want to install WITH or WITHOUT GeForce Experience.

**Comment by Yrlish** [comment]
@ElPumpo Have you killed this project? No commits since January.

**Comment by ElPumpo** [comment]
Its not killed its just that life happened. I'm working on other projects and don't spend the same amount of time on a PC as I used to back in the days.

**Comment by Yrlish** [comment]
Oh, I understand!

**Comment by ElPumpo** [comment]
Fixed in https://github.com/ElPumpo/TinyNvidiaUpdateChecker/commit/af010f4646dcf59d4543dd3646f39c6bc8b0192d
