### ISSUE TITLE
Download + Extract Not Working in Silent Mode

### ISSUE THREAD

**Issue by KZcheese** [ElPumpo/TinyNvidiaUpdateChecker#54]
When running in _Silent Mode_ from startup, selected _Download + Extract_ doesn't do anything. I believe this is because the prompt asking to user where to place the extracted installer is suppressed by silent mode.

Tested on a laptop with a GTX970m in optimus.

**Comment by Benji-Collins** [comment]
Same for me, Win 10 1803 GTX960m.

**Comment by ElPumpo** [comment]
If the extract mode for some reason isn't working then something is very wrong. Maybe the libary is missing? If y'all still active I'd like to get some telemetry so I can figure what happened for you guys, since this isn't a bug for the majority.

**Comment by KZcheese** [comment]
Hey I don’t seem to be having this problem anymore. Can’t speak for everyone else of course.
