### ISSUE TITLE
Doesn't seem like either WinRAR or 7-Zip is installed!

### ISSUE THREAD

**Issue by millionart** [ElPumpo/TinyNvidiaUpdateChecker#57]
> Doesn't seem like either WinRAR or 7-Zip is installed!
> The application will determinate 

> Do you want to disable the minimal install feature and use the traditional way?

**I use Bandizip for unzip, it's better than WinRAR or 7-Zip on Windows 10, please support it.**

**Comment by MrLint** [comment]
Perhaps for the sake of consistency and ease of coding it would be better to just embed 7za.exe into the package for local app use when unarchiving.

**Comment by carloshbcabral** [comment]
> Perhaps for the sake of consistency and ease of coding it would be better to just embed 7za.exe into the package for local app use when unarchiving.

I did this, https://github.com/carloshbcabral/TinyNvidiaUpdateChecker

**Comment by darealshinji** [comment]
You could also try to use 7zdec.exe from the LZMA SDK. It's a single binary (no 7z.dll needed) and only ~40k in size.

**Comment by ElPumpo** [comment]
It doesnt contain extracting sfx files if I remember correctly and the argument "is better" from OP wont cut it
