### ISSUE TITLE
The remote server returned an error 404

### ISSUE THREAD

**Issue by gindulis** [ElPumpo/TinyNvidiaUpdateChecker#62]
Please see the below image for the error message.

![image](https://user-images.githubusercontent.com/2493521/56593021-6ad0b880-65f4-11e9-81b1-da89d4cd6916.png)

**Comment by ElPumpo** [comment]
You scared me there for a second. Run the application with the `--debug` argument and then screenshot

**Comment by gindulis** [comment]
It seems this was only a temporary issue, cannot reproduce it anymore.

**Comment by ElPumpo** [comment]
Ok closing!
