### ISSUE TITLE
Implement support for DCH drivers

### ISSUE THREAD

**Issue by grynnan** [ElPumpo/TinyNvidiaUpdateChecker#63]
DCH Driver compability.
(DCH Drivers are common on Laptops that came with Win10 Preinstalled)

""DCH" (Declarative, Componentized, Hardware Support Apps) refers to new packages preinstalled by OEMS implementing the Microsoft Universal Driver paradigm.

DCH drivers cannot be installed over a standard system, and Standard drivers cannot be installed over a DCH system."

(See:
https://docs.microsoft.com/en-us/windows-hardware/drivers/what-s-new-in-driver-development#windows-driver-frameworks-wdf
)

**Comment by Enigmasdf** [comment]
Same problem here. DCH drivers installed on system, but the auto updater pulls the standard drivers and the installation fails.
