### ISSUE TITLE
Can no longer check for updates, error 404

### ISSUE THREAD

**Issue by jannispl** [ElPumpo/TinyNvidiaUpdateChecker#66]
![image](https://user-images.githubusercontent.com/838818/63367781-dfd2b580-c37c-11e9-9824-d1268746e0d9.png)

**Comment by niklaskorz** [comment]
This is an issue on NVIDIA's side, wait a few hours and it should work again

**Comment by niklaskorz** [comment]
To clarify, the issue is that the URL to the .exe returns a 404. If you go directly to NVIDIA's website and try to download the driver, you are redirected to the same 404ed URL.

**Comment by jannispl** [comment]
Alright, that clears it up. I've seen newer version '436.02' in the URL, that is why I initially thought they might have changed something up on their end.

**Comment by ElPumpo** [comment]
Lol youre giving me a heart attack, good it wasnt on my side
