### ISSUE TITLE
Show a warning/error when running with unsupported hardware

### ISSUE THREAD

**Issue by itsho** [ElPumpo/TinyNvidiaUpdateChecker#69]
Hi.

First - I'm really enjoying this wonderful tool! big thank you for all contributors!

As a continuation to  #50 (wrong update for unsupported hardware)

When running the app with unsupported hardware, for example:
* GeForce 630M
* GeForce 210

display an error or a warning message.

list of supported cards: https://github.com/ElPumpo/TinyNvidiaUpdateChecker/wiki/Supported-Graphics-Cards

**Comment by ElPumpo** [comment]
Accually what we need to implement is to properly get the IDs [here](https://github.com/ElPumpo/TinyNvidiaUpdateChecker/blob/620694e4db8b4cbf44fa2b8d4295a034a55c6f7c/TinyNvidiaUpdateChecker/MainConsole.cs#L552), then the application will always show the proper latest version available and not some hardcoded variable.

**Comment by ElPumpo** [comment]
Or query the nvidia API. Here's a project with a proper use https://github.com/ZenitH-AT/nvidia-update

**Comment by ElPumpo** [comment]
Implemented! New release soon
