### ISSUE TITLE
thanks

### ISSUE THREAD

**Issue by serossi** [ElPumpo/TinyNvidiaUpdateChecker#70]
contrary to usual complains and feature requests i want to take my time and thank the author

everytime i use it im so thankfully for this little utility.
spares me the atrosity of nvidias installer. works for me rock solid, low footprint, this should be default by nvidia.

thanks in the name for 10s of tousands saved hours by all your users. have a great 2020

**Comment by ElPumpo** [comment]
Wow what a nice guy! Thanks a lot for the complements, and I hope you enjoy my code! <3
