### ISSUE TITLE
Tiny Typo

### ISSUE THREAD

**Issue by Technetium1** [ElPumpo/TinyNvidiaUpdateChecker#77]
https://github.com/ElPumpo/TinyNvidiaUpdateChecker/blob/7484536deee5bce34a3579f700d5224bf85a7d6c/TinyNvidiaUpdateChecker/SettingManager.cs#L63
> happenes

Thank you for maintaining this project @ElPumpo!

**Comment by ElPumpo** [comment]
Nice find, thanks

**Comment by Technetium1** [comment]
Fixed in https://github.com/ElPumpo/TinyNvidiaUpdateChecker/commit/e8705e2ce272c077da3ce609240722bbe6ac37bf
