### ISSUE TITLE
Windows smart screen warning

### ISSUE THREAD

**Issue by dilutedspine** [ElPumpo/TinyNvidiaUpdateChecker#81]
Windows Defender Smart Screen thinks the application is Malware with the most recent update to the .exe.  Might not be fixable depending on what kind of permissions it's seeking to use, ect.

**Comment by dilutedspine** [comment]
Looks like it's due to being a "unrecognized app".  Might just need to green light it in defender.

**Comment by ElPumpo** [comment]
Yea there's nothing I can do about that.. right? It's basicly complaining about unsigned exe files, I'm not paying to get my exe files signed.
