### ISSUE TITLE
DCH not identified on a fresh install

### ISSUE THREAD

**Issue by vdurante** [ElPumpo/TinyNvidiaUpdateChecker#83]
I just installed Windows and decided to use TinyNvidiaUpdateChecker to get a fresh minimal installation of NVidia Drivers. 

Since this is a fresh install of Windows, `DCHUVen` is not set on registry, therefore it defaults to standard drivers. From my layman understanding, NVIDIA and Microsoft are pushing forward the DCH drivers, therefore DCH should be the default.

Alternatively,  if `DCHUVen` is not found during first run, maybe the application could request the list of recommended drivers from NVIDIA GeForce's website and check if the first download option is DCH or not.

**Comment by ElPumpo** [comment]
I was afraid about this...

**Comment by ElPumpo** [comment]
If DCHUVen is there then we should not be continuing the program. I am going to change the behaviour of TNUC so if detected it wont continue its program.

**Comment by ElPumpo** [comment]
https://github.com/ElPumpo/TinyNvidiaUpdateChecker/commit/fe888270137eb5c58a4dd71097c79b62e7e41e47

**Comment by ElPumpo** [comment]
Accually my understanding is that DCH drivers are in fact not required. And if you're not currently sporting them there's no need to force them either. Closing issue unless im wrong
