### ISSUE TITLE
System.IO.FileLoadException - could not load file or assembly 'System'

### ISSUE THREAD

**Issue by cassiano-g** [ElPumpo/TinyNvidiaUpdateChecker#84]
After a few weeks without updating my drivers I opened the .exe to find this message:
![image](https://user-images.githubusercontent.com/57730257/85600777-225fc100-b624-11ea-82c3-6c99b25d6fda.png)

The program shuts down after a couple of seconds.

I did a bit of searching and it seems there needs to be a reference to the 'system.windows.forms' file in the code somewhere. I know the screenshot above doesn't mention that file, but that's probably because I was trying to fix this myself with an assortment of tutorials, and after rebooting my machine the message changed to what you see now. 

The file itself _is_ present in my PC but it apparently can't be accessed.

I'm not a developer so I'm sorry if I wasn't clear enough. If there's anything else I need to inform just let me know.

**Comment by cassiano-g** [comment]
I'm running Windows 10 64 bit. I'll link my dxdiag file here in case there's something useful.

[DxDiag.txt](https://github.com/ElPumpo/TinyNvidiaUpdateChecker/files/4830819/DxDiag.txt)

**Comment by ElPumpo** [comment]
[A quick google shows that it's a fault on your computer](https://stackoverflow.com/questions/23903657/could-not-load-file-or-assembly-system-version-2-0-5-0-in-net-4-mvc-4-applicat)..

- make sure there's no .NET updates available in windows update
- try repairing all your .NET installations
- make sure .NET 4.6.1 is installed in the first place

![image](https://user-images.githubusercontent.com/12564301/85791311-e74bb380-b731-11ea-87aa-d167934b9179.png)

**Comment by cassiano-g** [comment]
Did a clean install of Windows 10 again and the problem is solved, indeed. My user had somehow lost permission to write in the windows Temp folder. How exactly that happened is lost to me, unfortunately. 

Thank you for your time regardless.

**Comment by ElPumpo** [comment]
Yea weird bug for sure, have a good one!
