### ISSUE TITLE
Nvidia installer is shown even in silent mode because of geforce experience being force installed

### ISSUE THREAD

**Issue by HatBeardZero** [ElPumpo/TinyNvidiaUpdateChecker#85]
1.13 runs a silent install but 1.14.1 does not.  is this by design or is something wrong?

**Comment by ElPumpo** [comment]
Which arguments are you parsing to TNUC?

**Comment by tomas-samot** [comment]
I believe I am getting the same time of issue. Since updating to the latest TNUC I get a driver install window from Nvidia. 

I did not have any arguments set before and I don't have any set now.

**Comment by HatBeardZero** [comment]
> Which arguments are you parsing to TNUC?

none.  if i use the 1.14.1 w/o any options it fails, but works fine in the same manner for 1.13

**Comment by ElPumpo** [comment]
Oh this is intended, because we cannot run it silent or it'll install Geforce experience (only happens if 'minimal install' is not enabled)

**Comment by Neobond** [comment]
> Oh this is intended, because we cannot run it silent or it'll install Geforce experience (only happens if 'minimal install' is not enabled)

Thanks for the explanation, this is the reason I stayed with 1.13 (although it did not install GeForce Experience ever) but now I have upgraded due to the URL changes and it's no longer silent.

Great little app btw thanks!

**Comment by ElPumpo** [comment]
Wait.. What?

**Comment by HatBeardZero** [comment]
it doesn't install GFE for me either on 1.13

**Comment by RationalSquash** [comment]
Just used 1.14.2 and had the same issue. When running the exe without any arguments, after clicking the "install now" button, it runs the installer and gives you the normal nvidia driver installer UI.

I quit the installer and retried a few times and confirmed it giving me the installer every time.

However, after checking the wiki and finding the arguments, I used --confirm-dl and --quiet. This made the installer no longer pop up! 

I've used 1.13 for a long time, and having the installer pop up by default on the new version is a bit annoying, and makes it harder to recommend/explain to non-tech people who are scared of stuff that doesn't work out of the box...

Is this a bug, or is this now the default?

**Comment by ElPumpo** [comment]
Hi @RationalSquash, do you mind running TNUC with the `--debug` command line argument added with your other ones and post your log here?

**Comment by ElPumpo** [comment]
Really weird @HatBeardZero and @Neobond since I had people complaining in a previous issue where Geforce experience was installed if the `--quiet` argument is used, and that's the reason to why it doesn't run the installer quietly if you don't have minimal installer enabled.

Maybe the geforce install is regionbased?

**Comment by RationalSquash** [comment]
> Hi @RationalSquash, do you mind running TNUC with the `--debug` command line argument added with your other ones and post your log here?

Well, the newest driver is already installed, so it's not going to install it but sure.

 
![image](https://user-images.githubusercontent.com/35276739/92270369-39eddc80-eee6-11ea-8c11-7ea725c214d2.png)

Running with --quiet kills the output, so no info there

**Comment by RationalSquash** [comment]
This is probably more useful:

![image](https://user-images.githubusercontent.com/35276739/92270872-0f505380-eee7-11ea-90c3-1cdafe58bbed.png)

**Comment by RationalSquash** [comment]
--quiet still gives the installer
![image](https://user-images.githubusercontent.com/35276739/92271247-c0ef8480-eee7-11ea-8cc0-d5bbe2a46e2c.png)

**Comment by RationalSquash** [comment]
No installer when adding --confirm-dl

**Comment by ElPumpo** [comment]
I must've fucked it up big time then, here's a recap on how TNUC is expected to behave

- If minimal installer is enabled and the quiet argument is used no installer should appear
- If minimal installer is disabled and the quiet argument is used a installer should appear
- Any other scenario the installer should appear. This is because I've had people reporting GeForce Experience being force installed if the graphics installer is quietly run

**Comment by Neobond** [comment]
For now I created a shortcut in the same folder and modified target to "<path to>\TinyNvidiaUpdateChecker.v1.14.2.exe" --confirm-dl 

Thanks for confirming this works (it does).

**Comment by nickpainter** [comment]
I just wanted to confirm that I also experienced the same issue as @RationalSquash.

**Comment by ElPumpo** [comment]
The reason to the NVIDIA driver installer being visible is because it caused issues since they changed their installer so it would always install Geforce Experience.

I must find a fix to still install them quietly (no NVIDIA installer visable) without having that shit installed, too.

**Comment by ElPumpo** [comment]
There's a `/gfexperienceinitiated` argument that will skip installing Geforce Experience. For people using the minimal installer it doesn't concern them. I've fixed this issue now, that force installing will show no dialog.

**Comment by Neobond** [comment]
Confirmed, my shortcut works installing in bg with no dialog again.
