### ISSUE TITLE
Wrong downloadURL. System.Net.WebException: The remote name could not be resolved: 'usload.nvidia.com'

### ISSUE THREAD

**Issue by geomih** [ElPumpo/TinyNvidiaUpdateChecker#86]
Running in debug mode, I get the following:

```
>TinyNvidiaUpdateChecker.v1.14.1.exe --debug
TinyNvidiaUpdateChecker v1.14.1

Copyright (C) 2016-2020 Hawaii_Beach
This program comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions. Licensed under GPLv3.

Arg: --debug

configFile: C:\Users\censored\AppData\Local\Hawaii_Beach\TinyNvidiaUpdateChecker\app.config
CHECK_UPDATE: true
MINIMAL_INSTALL: true
DOWNLOAD_LOCATION: us

Verifying internet connection . . . OK!

Verifying HAP MD5 hash . . . OK!
Generated hash: 24-1D-D8-58-41-D3-4F-88-92-3C-5A-BA-FD-D6-56-FB
Known hash:     24-1D-D8-58-41-D3-4F-88-92-3C-5A-BA-FD-D6-56-FB

winVer: 10
osID:   57
verOrg: 10.0.19041.0

langID:   1
cultName: en-US

Searching for Updates . . . OK!
offlineVer: 1.14.1
onlineVer:  1.14.1

Retrieving GPU information . . . ERROR!
System.Net.WebException: The remote name could not be resolved: 'usload.nvidia.com'
   at System.Net.HttpWebRequest.GetResponse()
   at TinyNvidiaUpdateChecker.MainConsole.GpuInfo()
downloadURL: http://usload.nvidia.com/Windows/451.67/451.67-notebook-win10-64bit-international-whql.exe
pdfURL:      https://us.download.nvidia.com/Windows/451.67/451.67-win10-win8-win7-release-notes.pdf
releaseDate: 09-Jul-20
downloadFileSize:  0 MB (0.00 bytes)
OfflineGPUVersion: 451.67
OnlineGPUVersion:  000.00
Your current GPU driver is newer than remote!
Your GPU drivers are up-to-date!

Job done! Press any key to exit.
```
Seems like the downloadURL is constructed wrongly.
If I try `http://us.download.nvidia.com/Windows/451.67/451.67-notebook-win10-64bit-international-whql.exe` in the browser the file can be downloaded.

**Comment by s-crypt** [comment]
I am also having the same issue. It also just started today.

**Comment by LuckyGray7** [comment]
No longer works for me either.

![image](https://user-images.githubusercontent.com/47206998/90260193-04326800-de00-11ea-9b6e-9cdcdd057b67.png)

**Comment by Groanworthy** [comment]
I fixed it for myself (as far as I can tell) by going to the app.config file in AppData\Local\Hawaii_Beach and changing the value of the "Download location" key from "us" to "us.down".

**Comment by LuckyGray7** [comment]
Thanks Groan that appears to have fixed it for me.

**Comment by geomih** [comment]
> 
> 
> I fixed it for myself (as far as I can tell) by going to the app.config file in AppData\Local\Hawaii_Beach and changing the value of the "Download location" key from "us" to "us.down".

This works. Thanks!

**Comment by Technetium1** [comment]
Another confirmation that `us.down` solves the problem. I'm hoping there's a new release soon.

**Comment by ElPumpo** [comment]
Uuuuum ripperino, lemme get a fix out!

**Comment by ElPumpo** [comment]
Um after some quick testing on the US server, I cannot reproduce this issue. Can anyone else reproduce the issue, or is it possibly some nvidia mistake?

**Comment by Technetium1** [comment]
![image](https://user-images.githubusercontent.com/9877150/90435694-5a700700-e09d-11ea-9445-07d15dbcbf46.png)
@ElPumpo

**Comment by ElPumpo** [comment]
- Where are y'all located, USA?
- Can more people provide a screenshot of TNUC with the `--debug` command line argument

**Comment by geomih** [comment]
@ElPumpo
I'm located in Central Europe.
For me, it is still failing with "us" and works fine with "us.down".

**Comment by LuckyGray7** [comment]
@ElPumpo I'm in Canada and it fails with "us" but works with "us.down"

**Comment by LuckyGray7** [comment]
@ElPumpo 
This is what I get with "us" and the --debug command line argument

![image](https://user-images.githubusercontent.com/47206998/90441623-217c6600-e08e-11ea-919e-dd9129f64e22.png)

**Comment by Technetium1** [comment]
Located in Michigan, also fails in North Carolina and Louisiana the same way.
![image](https://user-images.githubusercontent.com/9877150/90442219-4b428680-e0a8-11ea-8046-65d1e0c99c5d.png)
The Grey area is a censored account name.

**Comment by Technetium1** [comment]
I don't think that it should say newer than remote when it doesn't get an online version...

**Comment by Groanworthy** [comment]
I'm from the ME and got the same problem. Thing is, it didn't really matter what region you put in. If you pick US it'd look for usload.nvidia, if UK it'd look at ukload.nvidia, Germany it'd look at deload.nvidia etc etc...

That's how I figured out to try my ad-hoc fix. Since changing the region simply changed the start of the target url and the correct url had '.down' between your chosen region and the rest of the url, I simply added it to the key in app.config to see if that'll fix it, which it did. So basically I guess something screwed up with the program and made it look at 'location'load.nvidia.com instead of 'location'.download.nvidia.com

I'm not a programmer or anything so I have 0 idea how something like that could have happened.

**Comment by BlackX777** [comment]
changed it to "de.down"

**Comment by DeVaulted** [comment]
Germany here, changing de to de.down in the app.config file works.

**Comment by hl2guide** [comment]
Australia here:

```
Retrieving GPU information . . . ERROR!
System.Net.WebException: The remote name could not be resolved: 'ukload.nvidia.com'
   at System.Net.HttpWebRequest.GetResponse()
   at TinyNvidiaUpdateChecker.MainConsole.GpuInfo()
Your current GPU driver is newer than remote!
Your GPU drivers are up-to-date!
```

**Comment by ElPumpo** [comment]
Gotta give a shout out to y'all, you be killing it with the information. As said I assume nvidia changed something on their website that broke TNUC. What I dont understand is that I can't reproduce the issue.. I'll take a big dive tomorrow and try to fix it.

**Comment by Technetium1** [comment]
@ElPumpo Have you tried switching the DNS provider? I can confirm it happens with 8.8.8.8 and 1.1.1.1

**Comment by ElPumpo** [comment]
Okay new release v1.14.2 is released with the issue fixed. It turns out that nvidia changed the links on their website, which is easily fixed. Enjoy and thanks everyone for being active!
