### ISSUE TITLE
Scheduled powershell task ends with '0xC000013A' error code

### ISSUE THREAD

**Issue by Fooughhy** [ElPumpo/TinyNvidiaUpdateChecker#87]
I am trying to schedule TNUC to run at login. I do not believe there is an option to do so, and would simply like to try this out. I think I've previously put a shortcut in the Startup folder, but don't see why this shouldn't work. I am also doing this as I want the window to stay open. Therefore I want to run it through powershell, with the '-NoExit' parameter.

I schedule a task at login, and use powershell (version 7.0.3) for the application. I use the parameter field to put "-NoExit -File "C:\Users\fough\scoop\apps\tinynvidiaupdatechecker\current\TinyNvidiaUpdateChecker.exe"".

When this task is run, the following window appears. This seems like a weird error. [Powershell Window][1]

In Task Scheduler, the task has the error 0x40 if I use the full path for powershell, or 0xC000013A if I just use "pwsh.exe" as the application.

What am I doing wrong?

[1]: https://i.stack.imgur.com/s06wN.png

**Comment by ElPumpo** [comment]
I mean it's pretty clear. Powershell trows an error saying "Parser error: Missing closing `(` in expression"

**Comment by Fooughhy** [comment]
Please, can someone actually help me, instead of stating the most obvious thing ever? Like I am some kind of idiot... Truly not helpful or kind in any way.

Can you see any parentheses in that command? I am using a GUI, and only inputting the information I have given you in this post. I cannot accidentally have inserted a starting parenthesis in the code anywhere, as I am not writing a script. I have given you the information I have, and you try to solve it by stating the information I GAVE YOU?! Why is that?

**Comment by ElPumpo** [comment]
Haha you can take it however you want I don't give a damn, maybe my response was a bit dead but I wasn't bashing on you.

Okay maybe I didnt really read the error, seeing those weird characters make me wonder how is your file encoded? UTF-8?
