### ISSUE TITLE
choose-possibility of downlaod-folder

### ISSUE THREAD

**Issue by o0Julia0o** [ElPumpo/TinyNvidiaUpdateChecker#88]
a possiblity to choose the download-folder per argument or config-file would be great.
https://github.com/ElPumpo/TinyNvidiaUpdateChecker/wiki/Command-Line-Arguments

So you can manualle add a batch for silent installation(and so automatically delete all files instead of xy) before doing:
setup.exe /passive /nosplash /noeula /clean /noreboot

So if you wan´t to install only Driver + PhysX you can delete alle files per script, instead of:
Display.Driver
NVI2
PhysX
EULA.txt
license.txt
ListDevices.txt
setup.cfg
setup.exe

**Comment by ElPumpo** [comment]
You're talking about diffrerent things in the same issue, don't.

- For being able to install PhysX with minimal installer, see #28. I don't understand what you're meaning with deleting scripts
- Make a seperate issue for being able to choose configuration file path
- Make a seperate issue for choosing a download directory

**Comment by o0Julia0o** [comment]
thx, if TinyNvidiaUpdateChecker would download in a specific path, you sould delete "manually" (so with a script, batch) all not wanted files.

And then run the passive setup within the batch. So you have ha portable and 1click Nvidia-Driver Updater. With only the things you wan´t to have(f.e. driver + physx).

**Comment by o0Julia0o** [comment]
>     * For being able to install PhysX with minimal installer, see #28. I don't understand what you're meaning with deleting scripts

but no physx is installed whit this minimal-method.
