### ISSUE TITLE
Override driver download directory

### ISSUE THREAD

**Issue by o0Julia0o** [ElPumpo/TinyNvidiaUpdateChecker#89]
it would be usefull to have a possiblity to choose the download-folder per argument or config-file:
https://github.com/ElPumpo/TinyNvidiaUpdateChecker/wiki/Command-Line-Arguments

**Comment by ElPumpo** [comment]
When? For the auto install where it currently saves at `%temp%` ?

**Comment by o0Julia0o** [comment]
Yes, so if 1 pc in the network downloaded the files, the other pc don´t have to download the files again. You can just copy the files to a folder where all pcs in the network have access to.

**Comment by o0Julia0o** [comment]
but that´s using the working directory as path to the config file. You can´t choose a path in a network-folder f.e. - so if you have a lot of pcs to install, they all are looking for the same folder in the network.

**Comment by ElPumpo** [comment]
Not going to implement this. There's "Download Only" for this.

**Comment by o0Julia0o** [comment]
But you have to download it on every pc you manage again.

**Comment by ElPumpo** [comment]
Yes
