### ISSUE TITLE
Override configuration file path with argument

### ISSUE THREAD

**Issue by o0Julia0o** [ElPumpo/TinyNvidiaUpdateChecker#90]
it would be handy, if you could choose the configuration-file-path, f.e. with an argument.

**Comment by ElPumpo** [comment]
There's `--config-here`

**Comment by o0Julia0o** [comment]
but that´s using the working directory as path to the config file. You can´t choose a path in a network-folder f.e. - so if you have a lot of pcs to install, they all are looking for the same folder in the network.

**Comment by ElPumpo** [comment]
Added after three years😂
