### ISSUE TITLE
Possibility to choose hotfix & studio drivers

### ISSUE THREAD

**Issue by ShlomiD83** [ElPumpo/TinyNvidiaUpdateChecker#91]
can this amazing tool also check if Nvidia released hotfix drivers as well?

thanks!

**Comment by ElPumpo** [comment]
Hotfix drivers.. right, yea that could be a possiblity. But why would you want them?

**Comment by ShlomiD83** [comment]
I like to install the very latest drivers, even hotfix drivers.
maybe it could check and give an option to choose between the official driver and the hotfix drivers.

**Comment by ElPumpo** [comment]
Okay, I'm thinking a configuration thing with initial prompt with three choices

- Game ready drivers (normal)
- Studio drivers
- Beta drivers

But it seems like beta drivers are discontinued by nvidia?

**Comment by ShlomiD83** [comment]
@ElPumpo I think you are correct.
but they release hotfix drivers whenever is needed.

**Comment by ElPumpo** [comment]
But it looks like quite the task, because what if the user wants only beta drivers but a GRD (normal) driver is available that is newer? Wah you'd have to compare dates and- or versions to find out which one is most up to date so you don't recommend a old beta driver

**Comment by ElPumpo** [comment]
Also where are you finding beta drivers? 
![image](https://user-images.githubusercontent.com/12564301/118709504-57b56480-b81d-11eb-8951-4e2dd9b57f96.png)

I can't find beta drivers for this GPU, only one from 4 years ago

**Comment by ShlomiD83** [comment]
If it's too complicated you can close this ticket.
It's not something urgent, just a thought I had.

**Comment by ElPumpo** [comment]
Not gonna happen, beta drivers haven't been released in ages and studio drivers not really for the user who uses TNUC.
