### ISSUE TITLE
Error when nvidia website does not return driver download link

### ISSUE THREAD

**Issue by ghost** [ElPumpo/TinyNvidiaUpdateChecker#95]
An error is occuring, SSL/TLS.
disabled firewall check
internet access check
redownload program check
delete appdata hawaii beach check
ddu drivers check

````
TinyNvidiaUpdateChecker v1.14.2

Copyright (C) 2016-2020 Hawaii_Beach
This program comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions. Licensed under GPLv3.

Verifying internet connection . . . OK!

Verifying HAP MD5 hash . . . OK!

Retrieving GPU information . . . ERROR!
System.Net.WebException: The request was aborted: Could not create SSL/TLS secur
e channel.
   at System.Net.WebClient.OpenRead(Uri address)
   at TinyNvidiaUpdateChecker.MainConsole.GpuInfo()
System.ArgumentNullException: Value cannot be null.
Parameter name: uriString
   at System.Uri..ctor(String uriString)
   at HtmlAgilityPack.HtmlWeb.Load(String url)
   at TinyNvidiaUpdateChecker.MainConsole.GpuInfo()
Your current GPU driver is newer than remote!
Your GPU drivers are up-to-date!

Job done! Press any key to exit.
````

Anyone else have this issue, seems to be error with program. 
Thanks.

**Comment by 0Dragonmoon** [comment]
.netframework. also check.

**Comment by ElPumpo** [comment]
Weird, try running with the `--debug` command line argument

**Comment by 0Dragonmoon** [comment]
> Weird, try running with the `--debug` command line argument
````
C:\Users\Computer\Desktop\b>TinyNvidiaUpdateChecker.v1.14..exe --debug
TinyNvidiaUpdateChecker v1.14.2

Copyright (C) 2016-2020 Hawaii_Beach
This program comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions. Licensed under GPLv3.

Arg: --debug

configFile: C:\Users\Computer\AppData\Local\Hawaii_Beach\TinyNvidiaUpdateChecker
\app.config
CHECK_UPDATE: false
MINIMAL_INSTALL: true
DOWNLOAD_LOCATION: uk

Verifying internet connection . . . OK!

Verifying HAP MD5 hash . . . OK!
Generated hash: 24-1D-D8-58-41-D3-4F-88-92-3C-5A-BA-FD-D6-56-FB
Known hash:     24-1D-D8-58-41-D3-4F-88-92-3C-5A-BA-FD-D6-56-FB

winVer: 7
osID:   19
verOrg: 6.1.7601.65536

langID:   1
cultName: en-US

Retrieving GPU information . . . ERROR!
System.Net.WebException: The request was aborted: Could not create SSL/TLS secur
e channel.
   at System.Net.WebClient.OpenRead(Uri address)
   at TinyNvidiaUpdateChecker.MainConsole.GpuInfo()
System.ArgumentNullException: Value cannot be null.
Parameter name: uriString
   at System.Uri..ctor(String uriString)
   at HtmlAgilityPack.HtmlWeb.Load(String url)
   at TinyNvidiaUpdateChecker.MainConsole.GpuInfo()
downloadURL:
pdfURL:
releaseDate: 1/1/0001
downloadFileSize:  0 MB (0.00 bytes)
OfflineGPUVersion: 466.27
OnlineGPUVersion:  000.00
Your current GPU driver is newer than remote!
Your GPU drivers are up-to-date!

Job done! Press any key to exit.
````
this is my output. Thanks.

**Comment by ElPumpo** [comment]
Oh okay I seem to have missed a case like this when the nvidia website doesn't return a GPU driver download link for you, because there is none available. Instead of erroring out the program should say something like "the nvidia website did not provide a gpu driver available for your system". What GPU do you have, perhaps there's no driver available for Windows 7?

**Comment by 0Dragonmoon** [comment]
that sounds right, it started after i put an old gpu into my system ( i swapped out my 1080ti which has latest win7 drivers with a gtx 500series card which is discontinued) which is probably where this error come in. not sure if relevant to this program but its still happening even after switching gpu back to 1080ti and ddu the drivers etc maybe theres a second bug here.

**Comment by Snala** [comment]
I started receiving this error today. No graphics card changes have been made recently to hardware, though the 2022 November 8 Windows 10 update was just installed.  Here is the debug output:

C:\Users\riosd\Downloads>C:\Users\riosd\Downloads\TinyNvidiaUpdateChecker.v1.14.7.exe --debug
TinyNvidiaUpdateChecker v1.14.7

Arg: --debug

configFile: C:\Users\riosd\AppData\Local\Hawaii_Beach\TinyNvidiaUpdateChecker\app.config
CHECK_UPDATE: true
MINIMAL_INSTALL: true
DOWNLOAD_LOCATION: us

Verifying internet connection . . . OK!

Verifying HAP MD5 hash . . . OK!
Generated hash: F9-72-91-2B-04-C7-FD-13-B7-55-D9-57-B3-66-EB-3F
Known hash:     F9-72-91-2B-04-C7-FD-13-B7-55-D9-57-B3-66-EB-3F

winVer: 10
osID:   57
verOrg: 10.0.19045.0

langID:   1
cultName: en-US

Searching for Updates . . . OK!
offlineVer: 1.14.7
onlineVer:  1.14.7

Retrieving GPU information . . . ERROR!
System.UriFormatException: Invalid URI: The Authority/Host could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at HtmlAgilityPack.HtmlWeb.Load(String url)
   at TinyNvidiaUpdateChecker.MainConsole.GpuInfo()
gpuURL: https://www.nvidia.com/Download/processDriver.aspx?psid=98&pfid=756&osid=57&lid=1&dtcid=1&ctk=0
downloadURL:
pdfURL:
releaseDate: 1/1/0001
downloadFileSize:  0 MB (0.00 bytes)
OfflineGPUVersion: 522.25
OnlineGPUVersion:  000.00
Your current GPU driver is newer than remote!
Your GPU drivers are up-to-date!

Press any key to exit...
