### ISSUE TITLE
Check for currently installed version seems broken; detects 711.1 instead of 471.11

### ISSUE THREAD

**Issue by rahul-ramadas** [ElPumpo/TinyNvidiaUpdateChecker#96]
I just installed 471.11 today, and when I ran the tool again after restarting, it detected the currently installed version as 711.1 and said I need to update to 471.11.

![image](https://user-images.githubusercontent.com/2167984/122946789-82b83a00-d32e-11eb-9b31-2baa373ad552.png)

**Comment by rahul-ramadas** [comment]
Looks like you are using WMI to get the currently installed version. The `DriverVersion` value reported for my installation in the `Win32_VideoController` class is: **30.0.14.7111**

This bit of code seems to be making some assumptions about how many digits exist in each part of the version ([link](https://github.com/ElPumpo/TinyNvidiaUpdateChecker/blob/4c568d95749b61c50c24bd1b350d0b56a1bc2f8b/TinyNvidiaUpdateChecker/MainConsole.cs#L499)):

```
OfflineGPUVersion = obj["DriverVersion"].ToString().Replace(".", string.Empty).Substring(5);
OfflineGPUVersion = OfflineGPUVersion.Substring(0, 3) + "." + OfflineGPUVersion.Substring(3); // add dot
```

It breaks for this new version.

**Comment by burritosoftware** [comment]
> Looks like you are using WMI to get the currently installed version. The `DriverVersion` value reported for my installation in the `Win32_VideoController` class is: **30.0.14.7111**
> 
> This bit of code seems to be making some assumptions about how many digits exist in each part of the version ([link](https://github.com/ElPumpo/TinyNvidiaUpdateChecker/blob/4c568d95749b61c50c24bd1b350d0b56a1bc2f8b/TinyNvidiaUpdateChecker/MainConsole.cs#L499)):
> 
> ```
> OfflineGPUVersion = obj["DriverVersion"].ToString().Replace(".", string.Empty).Substring(5);
> OfflineGPUVersion = OfflineGPUVersion.Substring(0, 3) + "." + OfflineGPUVersion.Substring(3); // add dot
> ```
> 
> It breaks for this new version.

I'm not sure if the app seems to be maintained anymore: if you could make a fork with this and PR it, it might be better :/

**Comment by ElPumpo** [comment]
> I'm not sure if the app seems to be maintained anymore: if you could make a fork with this and PR it, it might be better :/

It's been four hours since the bug report was made

**Comment by burritosoftware** [comment]
> > I'm not sure if the app seems to be maintained anymore: if you could make a fork with this and PR it, it might be better :/
> 
> It's been four hours since the bug report was made

Nevermind then, sorry about that 😅

**Comment by ElPumpo** [comment]
https://github.com/ElPumpo/TinyNvidiaUpdateChecker/releases/tag/v1.14.3 Ok it's fixed for now, a better implementation is to interact with the nvidia apis that exist to fetch it. Needs rewriting for sure in the future.

Let's put the boat in the water and see if it sinks 🛥️
