### ISSUE TITLE
Missing lookup for optional Scoop installation directories

### ISSUE THREAD

**Issue by iipom** [ElPumpo/TinyNvidiaUpdateChecker#97]
When 7zip is installed via scoop, the extraction will fail as it's not able to locate the 7zip exe.
Maybe you could add a line in the config for 7zip location.

I realize this is kind of a scoop problem and not a TinyNvidiaUpdateChecker problem, but due to the way scoop works this is not really fixable from their end

**Comment by ElPumpo** [comment]
I'll have to investigate on this, TNUC is searching for the directories 7zip usally is installed in...

**Comment by ElPumpo** [comment]
How did you install 7zip using scoop? In what directory is 7zip located?

**Comment by MarcoPasqualini** [comment]
I will hijack this question and answer it myself, hopefully fixing @iipom problem too.

I looked at the TNUC code and it seems to be looking at the default scoop installation directories (which is the issue in my case).
I assume this means that most people using scoop will not have this issue.

It is possible to change the default scoop installation folders before installing scoop by setting some (local) environment variables before the setup. You can find some details [here](https://github.com/lukesampson/scoop#install-scoop-to-a-custom-directory-by-changing-scoop) and [here](https://github.com/lukesampson/scoop/wiki/Quick-Start#installing-scoop-to-custom-directory).

This means you could bypass the default scoop directory and generalize the code by using the same method scoop uses to check its own directory locations to verify 7-zip/winrar availability:
- [local](https://github.com/lukesampson/scoop/blob/3d67b7d37c4a2714e8942724d4677dcbd3678f01/lib/core.ps1#L967)
- [global](https://github.com/lukesampson/scoop/blob/3d67b7d37c4a2714e8942724d4677dcbd3678f01/lib/core.ps1#L970)

There are three options (here I reference the local scoop directory but it is mirrored for the global one):
1. $env:SCOOP - which is the environment variable you can set to use a custom installation directory
2. (get_config 'rootPath') - I believe this works if you use scoop internal configuration tool, but I am not sure
3. "$env:USERPROFILE\scoop" | Where-Object { -not [String]::IsNullOrEmpty($_) } | Select-Object -First 1 : the default directory

I assume the "fix" would be to check if $env:SCOOP and/or $env:SCOOP_GLOBAL exist and are set before falling back to the defaults.

**Comment by RichardLuo0** [comment]
Is the directory of 7-zip a necessity? It seems scoop will add 7z.exe into the PATH variable. If only 7z.exe is really what is needed then just use it directly.

**Comment by ElPumpo** [comment]
Yes I know this issue over a year old. To be honest the source code needs revisiting but I plan to iron out most opened issues here.

Well yea we only need the 7z.exe yes. I'll look into this some day

**Comment by ElPumpo** [comment]
Will fix it for the next update as I now have fixed the old mess 😀

**Comment by ElPumpo** [comment]
I have added the user `scoop` environment variable and also `scoop_global` global variable. Please report back on this new update if it resolved your issue as I don't use Scoop myself.

Thanks for waiting 2 years

**Comment by RichardLuo0** [comment]
I can confirm this works. Thank you

**Comment by ElPumpo** [comment]
Thanks for the follow up! I appreciate it.
