### ISSUE TITLE
Silent Uninstall

### ISSUE THREAD

**Issue by amirrabieyannejad** [ElPumpo/TinyNvidiaUpdateChecker#98]
hi, is there any switch to uninstall display Driver silently? 
after I install it using setup.exe -s -noreboot  silently. I'm using following command to unistall display.driver silently: 
"%systemroot%\System32\RunDll32.EXE" "%ProgramFiles%\NVIDIA Corporation\Installer2\InstallerCore\NVI2.DLL", UninstallPackage Display.Driver -silent -n
I realized that it will in appwiz.cpl properly disappeared but in the Path in Program Files some bunch of directory and files are already exist. (it is not happen when I Unistall the Program through wizard).  Is there any other way to silently uninstall display driver?

**Comment by ElPumpo** [comment]
Not related to TNUC, maybe try DDU I don't know.
